crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.http import request
#from django.views.generic import DetailView,ListView

from . import views


app_name='crm'

urlpatterns = [
    #login
    url(r'^$', views.login_view,  name='login'),
    url(r'^logout/', views.logoutview, name='logout'),



    #news
    url(r'^news/$', views.DashBoardView, name='news_index'),
    #url(r'^news/$', views.zaiyavka_Index_view, name='news_index'),
    url(r'^news/(?P<idd>[0-9]+)/$',views.news_detail_view, name='news_detail'),
    url(r'^news/edit(?P<idd>[0-9]+)/$', views.news_edit_view, name='news_edit'),
    url(r'^news/newnews/$', views.news_postform, name='news_newpost'),

    #flats
    url(r'^flats/newflat/$', views.flat_postForm, name='new_flat'),
    url(r'^flats/newflat_appart/$', views.flat_apparts_postForm, name='flat_apparts_postForm'),#new flat(only for appartaments)
    url(r'^flats/myflats_pub/$', views.my_flatview_pub, name='my_flatpub'), ## All Flats
    url(r'^flats/excl_flats_pub/$', views.excl_flatview_pub, name='excl_flatpub'), ## Exclusive Flats
    url(r'^flats/allflats_pub/$', views.all_flatview_pub, name='all_flatpub'),

    url(r'^flats/vestum/pup/(?P<idd>[0-9]+)/$',views.vestum_pub_view, name='Vs_pub'),
    url(r'^flats/all_vs_pub/$', views.vestum_All_pub_view, name = 'all_vs_pub'),

    url(r'^flats/Seo_flats_pub/$', views.all_flatviewSeo_pub, name='seo_flat_pub'),
    url(r'^flats/Seo_flats_Unpub/$', views.all_flatviewSeo_unpub, name='seo_flat_unpub'),
    url(r'^flats/allflats_pub_form/(?P<idd>[0-9]+)/$', views.seo_flat_pub, name='form_flatpub'),

    url(r'^flats/myflats_unpub/$', views.my_flatview_unpub, name='my_flatunpub'),
    url(r'^flat/edit(?P<idd>[0-9]+)/$', views.my_flatview_edit, name='flat_edit'),
    url(r'^flat/(?P<idd>[0-9]+)/$', views.myflatDetail, name='flat_detail'),
    url(r'^flat/print/(?P<idd>[0-9]+)/$', views.myflatPrint, name='flat_print'),
    url(r'^newFlatGal/(?P<idd>[0-9]+)/$',views.flat_photo_new_view, name='newFlatgal'),
    url(r'^flatdel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.flat_del_view, name='FlatPhotodel'),
    url(r'^flat_rotate/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.FlatPctRotateView, name='FlatPctRotate'),
    ##feeds
    url(r'^domclick.xml$', views.YandexFeedview, name='Yandex'),#for yandex feed
    url(r'^mail.xml$', views.MailRuFeedview, name='Mail'),  # for mail.ru feed
    url(r'^grFeed.xml$', views.GRFeedview, name='Yandex'),  # for yandex feed
    url(r'^domclick1.xml$', views.domclickfeedview, name='domclick'), #for domclick
    url(r'^vestum.xml$', views.vestumfeedview, name='vestumFeed'), #for Vestum 700
    url(r'^vestum300.xml$', views.vestumfeedview300, name='vestumFeed300'),  # for Vestum 300
    url(r'^vestumHouses.xml$', views.vestumFeedViewHouses, name='vestumHouses'),  # for Vestum Houses
    url(r'^sait.xml$', views.sait_vigr_view, name='domclick'), #for sait_feed
    url(r'^newyandex.xml$', views.NewYandexFeedview, name='NewYandex'),  # for New yandex feed(no Fakes)
    url(r'^newsait21.xml$', views.NewSaitFeedview, name='NewSait'),  # for New Sait(21 centry) feed(no Fakes)
    url(r'^afy.xml$', views.AfyFeedview, name='Afy'),  # for New yandex feed(no Fakes)
    ##any
    url(r'^domclick_index/$', views.domclick_Index_view, name='domclick_index'),
    url(r'^kdastr/(?P<idd>[0-9]+)/$', views.kadastr_edit, name='new_kadastr'),# new_kadastr_numb

    #clients
    url(r'^clients/newclient/$', views.new_client_view, name='new_client'),
    url(r'^clients/editclient/(?P<idd>[0-9]+)/$', views.edit_client_view, name='edit_client'),
    url(r'^clients/own_clients/$', views.own_clients_view, name='own_clienws'),
    url(r'^clients/all_clients/$', views.all_clients_view, name='all_clienws'),
    url(r'^clients/otd_clients/$', views.otd_clients_view, name='otd_clienws'),
    url(r'^client/(?P<idd>[0-9]+)/$', views.cliend_detail_view, name='client_detail'),

    #doma
    url(r'^new_dom/$', views.new_dom_view, name='new_dom_post'),
    url(r'^pub_unp_dom/$', views.mu_unpob_doma_view, name='upb_dom_view'),
    url(r'^pub_pub_dom/$', views.mu_pob_doma_view, name='pub_dom_view'),
    url(r'^doms/(?P<idd>[0-9]+)/$',views.dom_detail_view,name='dom_detail'),
    url(r'^doms/edit(?P<idd>[0-9]+)/$', views.domaeditview, name='dom_edit'),
    url(r'^doms/print/(?P<idd>[0-9]+)/$',views.dom_print_view,name='dom_print'),
    url(r'^doms/pct_del/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.house_del_view,name='dom_pct_del'),

    #uchastki
    url(r'^new_uch/$', views.new_uc_view, name='new_uch_post'),
    url(r'^pub_uch/$',views.pup_uchastki,name='pub_uc_index'),
    url(r'^un_uch/$',views.unpup_uchastki,name='unpub_uc_index'),
    url(r'^uch/(?P<idd>[0-9]+)/$',views.uch_detail_view,name='uc_detail'),
    url(r'^uchprt/(?P<idd>[0-9]+)/$',views.uch_print_view,name='uc_print'),
    url(r'^uch/edit(?P<idd>[0-9]+)/$', views.ucheditview, name='uc_edit'),
    url(r'^uch/delete/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$', views.uchastok_del_view, name='uc_delete'),

    #Commerce
    url(r'^commerce/new$', views.NewCommerceView, name='new_commerce_url'),
    url(r'^commerce/my/index$', views.MyIndexCommerceView, name='my_index_commerce_url'),
    url(r'^commerce/all/index$', views.AllIndexCommerceView, name='all_index_commerce_url'),
    url(r'^commerce/detail/(?P<idd>[0-9]+)$', views.DetailCommerceView, name='detail_commerce_url'),
    url(r'^commerce/edit/(?P<idd>[0-9]+)$', views.EditCommerceView, name='edit_commerce_url'),

    #otchet
    url(r'^newotchet/$',views.new_otchet_view_All, name='otch_new_all'),
    url(r'^editotchet/(?P<idd>[0-9]+)/$', views.otchet_edit_view, name='otch_edit'),
    url(r'^allochet(?P<tpr_tab>[0-9]+)/$',views.reeelt_otchet_all_view, name='otch_all_reelt'),
    url(r'^sdelka/(?P<idd>[0-9]+)/$', views.reelt_sdelka_otchet_detail_view, name='otch_detail'),
    url(r'^sdelka/zakrit/(?P<idd>[0-9]+)/$',views.sdelka_zakritie_view, name='sdelka_zakr'),
    url(r'^sdelka/sriv/(?P<idd>[0-9]+)/$',views.sdelka_sriv_view, name='sdelka_sriv'),
    url(r'^sdelka/rasr/(?P<idd>[0-9]+)/$',views.sdelka_rasroch_view, name='sdelka_rasr'),
    url(r'^sdelka/delete/(?P<idd>[0-9]+)/$',views.sdelka_delete_view, name='sdelka_del'),
    url(r'^totchet/$', views.tempFioView,name='1'),#all fio in sdelka edit
    url(r'^testotch/$',views.kach_otch_view,name='DmCahestvoOtch'), #temp for domck kachestvo
    url(r'^perenos_groups/$',views.temp_otch_view, name='tempGroupOtchet'), #for perenos groups

    # feeds
    url(r'^cian.xml$', views.cianfeedview, name='cian'),
    url(r'^ncian.xml$', views.cianfeedview1, name='cian'),#new cian feed
    url(r'^megareal.xml$', views.MegaRealfeedview, name='mega'),
    url(r'^new/$',views.newvigrView, name='newvigr'),
    url(r'^nnew/$',views.newvigrNovostroikaView , name='newNovvigr'),
    url(r'^newviggal/(?P<idd>[0-9]+)/$',views.newVigGalView, name='newvigrgal'),
    url(r'^cianindex/$', views.cianindexview, name='cianindex'),
    url(r'^cianindexup/$', views.cianindexUPview, name='cianindexupl'),
    url(r'^cianedit/(?P<idd>[0-9]+)/$',views.cianedit, name='cianedit'),
    url(r'^ciandels/(?P<idd>[0-9]+)/$',views.cianDelviewSubjct, name='ciandelsubj'),
    url(r'^ciandel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.ciandelview, name='ciandel'),

    #Zayavki
    url(r'^zayavka/new/$',views.New_Zayavka_View, name='NewZayav'),
    url(r'^zayavka/new_nov/$', views.New_Nov_Zayavka_View, name='NewZayavNov'),
    url(r'^zayavka/new_nov_lich/$', views.lich_rielt_Zayavka_View, name='NewZayavLich'),
    url(r'^index/$',views.zaiyavka_Index_view, name='indexZayavka'),
    url(r'^zayavka/vzyat/(?P<idd>[0-9]+)/$', views.zayavka_vzyata_view, name='VzyatZayav'),
    url(r'^zayavka/sdelka/(?P<idd>[0-9]+)/$', views.zayavka_sdelka_view, name='SdelkaZayav'),
    url(r'^zayavka/sriv/(?P<idd>[0-9]+)/$', views.zayavka_sriv_view, name='SdelkaSriv'),

    #statistika
    url(r'^stat_obj/$', views.stat_count_crm_obj, name='crm_obj_index'),
    url(r'^stat_obj_past/$', views.stat_count_crm_obj_past, name='crm_obj_past_index'),
    url(r'^stat_obj_adler/$', views.stat_count_crm_obj_adler, name='crm_obj_index_adler'),
    url(r'^stat_obj_past_adler/$', views.stat_count_crm_obj_past_adler, name='crm_obj_past_index_adler'),
    url(r'^sdelkaReiting/(?P<year_pr>[0-9]+)/$', views.new_reyting_po_sdelkam,
        name='New_Sdelka_Reit'),
    url(r'^stat_obj/report_in_otdel/(?P<group_pk>[0-9]+)/$', views.ReportInOtdelView, name='report_in_otdel_html'),#
    url(r'^stat_obj/report_in_otdel/all/$', views.ReportAllRieltsView, name='report_all_html'),
    url(r'^stat_obj/report_in_otdel/otdels/$', views.ReportOtdelsView, name='report_otdels_html'),
    url(r'^stat_obj/report_in_otdel/agent/(?P<agent_id>[0-9]+)/$', views.ReportAgentObjectsView, name='agent_report_in_otdel_html'),

    #for homka admin
    url(r'^myadm/$', views.my_admi_view, name = 'myadm'),
    url(r'^myadm/usrbals/(?P<idd>[0-9]+)/$',views.UserBallsAddView, name='usrbalsadd'),
    url(r'^myadm/agent_id/(?P<agent_id>[\w\-]+)/$', views.AgentObjectsView, name='agent_id_url'),
    url(r'^myadm/admin/agent_id/(?P<agent_id>[\w\-]+)/$', views.AdminAgentObjectsView, name='admin_agent_id_url'),
    url(r'^myadm/user_edit/(?P<agent_id>[\w\-]+)/$', views.UserEditView, name='user_edit_url'),
    url(r'^myadm/user_new/$', views.UserNewView, name='user_new_url'),

    # Phone Calls Views
    url(r'^myadm/admin_phone_calls/$', views.AdminPhoneView, name='adm_phone_call'),
    url(r'^myadm/department_phone_calls/(?P<idd>[\w\-]+)/$', views.DepatmentPhoneView, name='department_phone_call'),
    url(r'^myadm/user_phone_calls/(?P<idd>[\w\-]+)/$', views.UserPhoneView, name='user_phone_call'),

    # for Dashboard
    url(r'^dashboard/$', views.DashBoardView, name='DashBoard'),

    #Domcklic texts
    url(r'^dm/index/$', views.dmIndexView, name='dm_index'),
    url(r'^dm/edit/(?P<idd>[0-9]+)/$', views.EditDMtextView, name='dm_edit'),

zvonki/urls.py
from django.conf.urls import url

from . import views

app_name = 'zvn'

urlpatterns = [
    url(r'^index/', views.zv_index_view,  name='index'),
    #url(r'^edit/(?P<idd>[0-9]+)/$', views.edit_zvn_view, name='edit'),
    url(r'^perez/(?P<idd>[0-9]+)/$', views.pr_status_zvn_view, name='perez'),
    url(r'^nd/(?P<idd>[0-9]+)/$', views.nd_status_zvn_view, name='nd'),
    url(r'^work/(?P<idd>[0-9]+)/$', views.work_status_zvn_view, name='work'),
    url(r'^arh/(?P<idd>[0-9]+)/$', views.arh_status_zvn_view, name='arh'),
    url(r'^all/(?P<idd>[0-9]+)/$', views.for_all_status_zvn_view, name='all'),
    #url(r'^new/$', views.new_tel_save_view, name='new')
    ]

zvonki/models.py
from datetime import timezone, datetime
from multiselectfield import MultiSelectField
from django.core.validators import MinValueValidator
from django.db import models


class zvonok(models.Model):
    auth = models.ForeignKey('auth.User', verbose_name='Риелтор:', on_delete=models.CASCADE, )
    date_sozd = models.DateTimeField(auto_now=False, verbose_name='Дата создания:')
    tel = models.IntegerField('Телефон',help_text='9881112233', blank=False)
    raion_choise = (('Выбор района', 'Выбор района'),('Ахун', 'Ахун'),('Бытха', 'Бытха'),('Виноградная', 'Виноградная'),('Дагомыс', 'Дагомыс'),('Донская', 'Донская'),('Донская(Пасечная)', 'Донская(Пасечная)'),
        ('Донская(Тимерязева)', 'Донская(Тимерязева)'), ('Завокзальный', 'Завокзальный'),('Заречный', 'Заречный'), ('Клубничная', 'Клубничная'),('КСМ', 'КСМ'),
        ('Красная поляна', 'Красная поляна'),('Кудепста', 'Кудепста'), ('Макаренко', 'Макаренко'),('Мамайка', 'Мамайка'),
        ('Мамайский перевал', 'Мамайский перевал'),('Мацеста', 'Мацеста'),('Н.Сочи', 'Н.Сочи'),('Объезная', 'Объезная'),
        ('Пластунская', 'Пластунская'),('Приморье', 'Приморье'), ('Раздольное', 'Раздольное'), ('Светлана', 'Светлана'),('Соболевка', 'Соболевка'),('Транспортная', 'Транспортная'),
        ('Фабрициуса', 'Фабрициуса'), ('Хоста', 'Хоста'), ('Центр', 'Центр'),
        ('(А) Блиново(+Вес)', '(А) Блиново(+Вес)'), ('(А) Гол. дали', '(А) Гол. дали'),
        ('(А) Кур.гор(+Чкал)', '(А) Кур.гор(+Чкал)'), ('(А) Мирный', '(А) Мирный'),
        ('(А) Молдовка', '(А) Молдовка'), ('(А) Центр', '(А) Центр'), ('(А) Чай совхоз', '(А) Чай совхоз'),
    )
    raion=MultiSelectField('Район', choices=raion_choise, max_length=20 , default='Неважно', blank=False)
    subj_choise = (('Неважно','Неважно'),('Студия','Студия'),('Однокомнатная','Однокомнатная'),
                   ('Двухкомнатная','Двухкомнатная'),('Многокомнатная','Многокомнатная'),
                   ('Дом','Дом'),('Участок','Участок'),('Коммерция','Коммерция'))
    subj = models.CharField(verbose_name='Что ищет:', max_length=50, choices=subj_choise, default='Неважно', blank=False)
    cena = models.IntegerField(verbose_name='Бюджет до:', validators=[MinValueValidator(300000)], blank=False, default=800000)
    client_name = models.CharField('Имя клиента:', max_length=45, blank=False)
    prim = models.TextField('Первичная информация:', blank=False)
    coment = models.TextField('Коментарий по проделанной работе', blank=False)
    status_choises = (('Новый','Новый'),('Перезвонить','Перезвонить'),('Недозвонился','Недозвонился'),('В работе','В работе'),
                      ('Архив','Архив'),('В общем доступе','В общем доступе'))
    status_zvonka = models.CharField(max_length=55, verbose_name='Статус звонка', choices =  status_choises, default='Новый')
    prezvonit = models.DateTimeField(verbose_name='Перезвонить: ', blank=False, )#default=datetime.now())

    def __str__(self):
        return self.client_name
    class Meta:
        verbose_name = 'Звонки риелторам'
        verbose_name_plural = 'Звонки риелторам'

zvonki/forms.py
from .models import zvonok
from django import forms
from django.core.exceptions import ValidationError

zvonki/views.py
from datetime import timezone, datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from zvonki.models import zvonok
from django.forms import modelformset_factory,  Textarea
from datetimepicker.widgets import DateTimePicker

##################
# index of zvonki
##################

@login_required
def zv_index_view(request):
    n1='CRM'
    n2 ='222'
    nzvn = modelformset_factory(zvonok, fields=('tel', 'client_name', 'subj', 'cena', 'status_zvonka',
                                                'prezvonit', 'coment', ),
                                        widgets={'prezvonit':  DateTimePicker(options={'format': '%Y-%m-%d %H:%M',
	                                            'language': 'ru-ru',}),
                                            'coment': Textarea(attrs={'rows': 80, 'cols': 20})},
                                        extra=1,)
    nzvn_formset = nzvn(queryset=zvonok.objects.all())
    if request.POST:
        nformset = nzvn(request.POST,request.FILES)
        if nformset.is_valid():
            nformset.save()
    return render(request,'zvonki/index.html',{'tn1':n1,'tn2':n2, 'nformset':nzvn_formset })


@login_required
def pr_status_zvn_view(request, idd):
    zvn = get_object_or_404(zvonok , pk = idd)
    zvn.status_zvonka = 'Перезвонить'
    zvn.save()
    return redirect('zvn:index')

@login_required
def nd_status_zvn_view(request, idd):
    zvn = get_object_or_404(zvonok , pk = idd)
    zvn.status_zvonka = 'Недозвонился'
    zvn.save()
    return redirect('zvn:index')

@login_required
def work_status_zvn_view(request, idd):
    zvn = get_object_or_404(zvonok , pk = idd)
    zvn.status_zvonka = 'В работе'
    zvn.save()
    return redirect('zvn:index')

@login_required
def arh_status_zvn_view(request, idd):
    zvn = get_object_or_404(zvonok , pk = idd)
    zvn.status_zvonka = 'Архив'
    zvn.save()
    return redirect('zvn:index')

@login_required
def for_all_status_zvn_view(request, idd):
    zvn = get_object_or_404(zvonok , pk = idd)
    zvn.status_zvonka = 'В общем доступе'
    zvn.save()
    return redirect('zvn:index')

templates/zvonki/admin_phones.html
{% extends 'crm/main.html' %}
{% block content %}
<div class="row">
   <div class="col s12 ">
      <div class="card ">
         <div class="card-content ">
            <table class="table">
               <thead>
               </thead>
               <tbody>
                  {% for department in departments %}
                  <tr>
                     <th scope="row">
                        <li><a href="{% url 'crm:department_phone_call' idd=department.pk %}">{{ department.name }} </a></li>
                     </th>
{#                  <td>2</td>#}
                  </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/zvonki/department_phones.html
{% extends 'crm/main.html' %}
{% block content %}
<div class="row">
   <div class="col s12 ">
      <div class="card ">
         <div class="card-content ">
            <table class="table">
               <thead>
               </thead>
               <tbody>
                  {% for user in users %}
                  <tr>
                     <th scope="row">
                        <li><a href="{% url 'crm:user_phone_call' idd=user.pk %}">{{ user.last_name }} {{ user.first_name }}
                        {{ user.userprofile1.tel }}</a></li>
                     </th>
{#                  <td>2</td>#}
                  </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/zvonki/edit.html
{% extends 'crm/main.html' %}
{% block content %}
{%  ifequal request.user pCall.auth %}
  <div class="row">
    <div class="col s12 ">
      <div class="card ">
        <div class="card-content ">
          <span class="card-title">{{ pCall.client_name }} / {{ pCall.cena }} руб./ {{ pCall.tel }}</span>
          <p>
             <table>
                    <tbody>
                        <tr>
                        <td><strong>Район:</strong></td>
                        <td></td>
                        </tr>
                        <tr>
                        <td><strong>Что ищет:</strong></td>
                        <td>{{ pCall.subj }}</td>
                        </tr>
                     <tbody>
             </table>
              <strong>Первичная информация:</strong> </br> {{ pCall.prim }} </p></br>


{% load material_form %}
    <div class="row">
         <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form method="post" class="post-form">
                    {% csrf_token %}
                        {% form form=tForm layout=form.layout %}{% endform %}
                        <button type="submit" name="_submit" class="btn">Сохранить</button>
                </div>
            </div>
         </div>
     </div>
</form>


        </div>
        <div class="card-action">
          <a href="{% url 'zvn:perez' idd=pCall.pk %}">Перезвонить</a>
          <a href="{% url 'zvn:nd' idd=pCall.pk %}">Недозвонился</a>
          <a href="{% url 'zvn:work' idd=pCall.pk %}">В работу</a>
          <a href="{% url 'zvn:arh' idd=pCall.pk %}">В архив</a>
          <a href="{% url 'zvn:all' idd=pCall.pk %}">В общий доступ</a>
        </div>
      </div>
    </div>
  </div>
{% endifequal %}
{% endblock %}

templates/zvonki/from.html
{% extends 'crm/main.html' %}

{% block content %}

{% load material_form %}

    <form method="post" class="post-form" xmlns="http://www.w3.org/1999/html">
                    {% csrf_token %}
                         {% for form in tform %}
    <div class="row">
         <div class="col s12">
            <div class="card">
                <div class="card-content">

    <div class="row">
      <div class="col s2"><strong>Тел. клиента:</strong>{{ form.tel }}</div>
      <div class="col s2"><strong>Имя клиента:</strong>{{ form.client_name }}</div>
      <div class="col s2"><strong>Что ищет:</strong>{{ form.subj }}</div>
      <div class="col s2"><strong>Цена:</strong>{{ form.cena }}</div>
      <div class="col s2"><strong>Статус:</strong>{{ form.status_zvonka }}</div>

      <div class="col s2" id="sub"><strong>Когда перезвонить:</strong>{{ form.prezvonit }}</div>
        <div class="row">
            <div class="col s10"><strong>Коментарий:</strong>{{ form.coment }}</div>
            <div class="col s2"><button type="submit" name="_submit" class="btn">Сохранить</button></div>
        </div>
    </div>
            </div>

            </div>
         </div>
     </div>
                        {% endfor %}

</form>





{% endblock %}

templates/zvonki/index.html
{% extends 'crm/main.html' %}
{% block content %}
    <div class="row">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s2">
                    <a class="active" href="#test1">Новые</a>
                </li>
                <li class="tab col s2">
                    <a href="#test2">Перезвонить</a>
                </li>
                <li class="tab col s2 ">
                    <a href="#test3">Недозвонился</a>
                </li>
                <li class="tab col s2">
                    <a href="#test4">В работе</a>
                </li>
                <li class="tab col s2">
                    <a href="#test5">Архив</a>
                </li>
                <li class="tab col s2">
                    <a href="#test6">В общем доступе</a>
                </li>
            </ul>
        </div>
        {#  Новые #}
        <div id="test1" class="col s12">

            <div class="row">
                <div class="col s12 ">
                    <div class="card blue lighten-4 darken-0">
                        <div class="card-content ">
                            <span class="card-title">Новый звонок</span>
                            <p>I am a very simple card. I am good at containing small bits of information. I
                                am convenient because I require little markup to use effectively.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content ">
                            <form method="post">
                                {{ nformset.management_form }}
                                {% for form in nformset %}
                                    {% csrf_token %}
                                    {{ form.id }}
                                    <li>{{ form.tel }}</li>
                                    <li>{{ form.ch1 }}</li>
                                    <div class="col s2">
                                        <button type="submit" name="_submit" class="btn">Сохранить</button>
                                    </div>
                                </ul>
                            {% endfor %}
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>

    {# Перезвонить  #}
    <div id="test2" class="col s12">Test 2</div>
    {# Недозвонился #}
    <div id="test3" class="col s12">Test 3</div>
    {# В работе #}
    <div id="test4" class="col s12">Test 4</div>
    {# Архив #}
    <div id="test5" class="col s12">Test 5</div>
    {# В общем доступе #}
    <div id="test6" class="col s12">Test 6</div>
</div>
{% endblock %}

templates/zvonki/user_phones.html
{% extends 'crm/main.html' %}
{% block content %}
<div class="row">
   <div class="col s12 ">
      <div class="card ">
         <div class="card-content ">
                 <form method="post" class="post-form" xmlns="http://www.w3.org/1999/html">
                    {% csrf_token %}
                     {{ search_form.as_p }}
                     <div class="col s2"><button type="submit" name="_call_search" class="btn">Поиск</button></div>
                 </form>
         </div>
      </div>
   </div>
</div>
<div class="row">
   <div class="col s12 ">
      <div class="card ">
         <div class="card-content ">
            <table class="table">
               <thead>
                  <tr>
                     <th scope="col">Входящий</th>
                     <th scope="col">Продолжительность</th>
                     <th scope="col"></th>
{#                     <th scope="col">Handle</th>#}
                  </tr>
               </thead>
               <tbody>
               {% for phone_call in calls_array %}
                  <tr>
                     <th scope="row">{{ phone_call.0 }}</th>
                     <td>{{ phone_call.1 }} мин.</td>
                     <td><a href="{{ phone_call.2 }}" class="button" target="_blank">Скачать</a></td>
{#                     <td>@mdo</td>#}
                  </tr>
               {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>
{% endblock %}