crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.http import request
#from django.views.generic import DetailView,ListView

from . import views


app_name='crm'

urlpatterns = [
    #login
    url(r'^$', views.login_view,  name='login'),
    url(r'^logout/', views.logoutview, name='logout'),



    #news
    url(r'^news/$', views.DashBoardView, name='news_index'),
    #url(r'^news/$', views.zaiyavka_Index_view, name='news_index'),
    url(r'^news/(?P<idd>[0-9]+)/$',views.news_detail_view, name='news_detail'),
    url(r'^news/edit(?P<idd>[0-9]+)/$', views.news_edit_view, name='news_edit'),
    url(r'^news/newnews/$', views.news_postform, name='news_newpost'),

    #flats
    url(r'^flats/newflat/$', views.flat_postForm, name='new_flat'),
    url(r'^flats/newflat_appart/$', views.flat_apparts_postForm, name='flat_apparts_postForm'),#new flat(only for appartaments)
    url(r'^flats/myflats_pub/$', views.my_flatview_pub, name='my_flatpub'), ## All Flats
    url(r'^flats/excl_flats_pub/$', views.excl_flatview_pub, name='excl_flatpub'), ## Exclusive Flats
    url(r'^flats/allflats_pub/$', views.all_flatview_pub, name='all_flatpub'),

    url(r'^flats/vestum/pup/(?P<idd>[0-9]+)/$',views.vestum_pub_view, name='Vs_pub'),
    url(r'^flats/all_vs_pub/$', views.vestum_All_pub_view, name = 'all_vs_pub'),

    url(r'^flats/Seo_flats_pub/$', views.all_flatviewSeo_pub, name='seo_flat_pub'),
    url(r'^flats/Seo_flats_Unpub/$', views.all_flatviewSeo_unpub, name='seo_flat_unpub'),
    url(r'^flats/allflats_pub_form/(?P<idd>[0-9]+)/$', views.seo_flat_pub, name='form_flatpub'),

    url(r'^flats/myflats_unpub/$', views.my_flatview_unpub, name='my_flatunpub'),
    url(r'^flat/edit(?P<idd>[0-9]+)/$', views.my_flatview_edit, name='flat_edit'),
    url(r'^flat/(?P<idd>[0-9]+)/$', views.myflatDetail, name='flat_detail'),
    url(r'^flat/print/(?P<idd>[0-9]+)/$', views.myflatPrint, name='flat_print'),
    url(r'^newFlatGal/(?P<idd>[0-9]+)/$',views.flat_photo_new_view, name='newFlatgal'),
    url(r'^flatdel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.flat_del_view, name='FlatPhotodel'),
    url(r'^flat_rotate/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.FlatPctRotateView, name='FlatPctRotate'),
    ##feeds
    url(r'^domclick.xml$', views.YandexFeedview, name='Yandex'),#for yandex feed
    url(r'^mail.xml$', views.MailRuFeedview, name='Mail'),  # for mail.ru feed
    url(r'^grFeed.xml$', views.GRFeedview, name='Yandex'),  # for yandex feed
    url(r'^domclick1.xml$', views.domclickfeedview, name='domclick'), #for domclick
    url(r'^vestum.xml$', views.vestumfeedview, name='vestumFeed'), #for Vestum 700
    url(r'^vestum300.xml$', views.vestumfeedview300, name='vestumFeed300'),  # for Vestum 300
    url(r'^vestumHouses.xml$', views.vestumFeedViewHouses, name='vestumHouses'),  # for Vestum Houses
    url(r'^sait.xml$', views.sait_vigr_view, name='domclick'), #for sait_feed
    url(r'^newyandex.xml$', views.NewYandexFeedview, name='NewYandex'),  # for New yandex feed(no Fakes)
    url(r'^newsait21.xml$', views.NewSaitFeedview, name='NewSait'),  # for New Sait(21 centry) feed(no Fakes)
    url(r'^afy.xml$', views.AfyFeedview, name='Afy'),  # for New yandex feed(no Fakes)
    ##any
    url(r'^domclick_index/$', views.domclick_Index_view, name='domclick_index'),
    url(r'^kdastr/(?P<idd>[0-9]+)/$', views.kadastr_edit, name='new_kadastr'),# new_kadastr_numb

    #clients
    url(r'^clients/newclient/$', views.new_client_view, name='new_client'),
    url(r'^clients/editclient/(?P<idd>[0-9]+)/$', views.edit_client_view, name='edit_client'),
    url(r'^clients/own_clients/$', views.own_clients_view, name='own_clienws'),
    url(r'^clients/all_clients/$', views.all_clients_view, name='all_clienws'),
    url(r'^clients/otd_clients/$', views.otd_clients_view, name='otd_clienws'),
    url(r'^client/(?P<idd>[0-9]+)/$', views.cliend_detail_view, name='client_detail'),

    #doma
    url(r'^new_dom/$', views.new_dom_view, name='new_dom_post'),
    url(r'^pub_unp_dom/$', views.mu_unpob_doma_view, name='upb_dom_view'),
    url(r'^pub_pub_dom/$', views.mu_pob_doma_view, name='pub_dom_view'),
    url(r'^doms/(?P<idd>[0-9]+)/$',views.dom_detail_view,name='dom_detail'),
    url(r'^doms/edit(?P<idd>[0-9]+)/$', views.domaeditview, name='dom_edit'),
    url(r'^doms/print/(?P<idd>[0-9]+)/$',views.dom_print_view,name='dom_print'),
    url(r'^doms/pct_del/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.house_del_view,name='dom_pct_del'),

    #uchastki
    url(r'^new_uch/$', views.new_uc_view, name='new_uch_post'),
    url(r'^pub_uch/$',views.pup_uchastki,name='pub_uc_index'),
    url(r'^un_uch/$',views.unpup_uchastki,name='unpub_uc_index'),
    url(r'^uch/(?P<idd>[0-9]+)/$',views.uch_detail_view,name='uc_detail'),
    url(r'^uchprt/(?P<idd>[0-9]+)/$',views.uch_print_view,name='uc_print'),
    url(r'^uch/edit(?P<idd>[0-9]+)/$', views.ucheditview, name='uc_edit'),
    url(r'^uch/delete/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$', views.uchastok_del_view, name='uc_delete'),

    #Commerce
    url(r'^commerce/new$', views.NewCommerceView, name='new_commerce_url'),
    url(r'^commerce/my/index$', views.MyIndexCommerceView, name='my_index_commerce_url'),
    url(r'^commerce/all/index$', views.AllIndexCommerceView, name='all_index_commerce_url'),
    url(r'^commerce/detail/(?P<idd>[0-9]+)$', views.DetailCommerceView, name='detail_commerce_url'),
    url(r'^commerce/edit/(?P<idd>[0-9]+)$', views.EditCommerceView, name='edit_commerce_url'),

    #otchet
    url(r'^newotchet/$',views.new_otchet_view_All, name='otch_new_all'),
    url(r'^editotchet/(?P<idd>[0-9]+)/$', views.otchet_edit_view, name='otch_edit'),
    url(r'^allochet(?P<tpr_tab>[0-9]+)/$',views.reeelt_otchet_all_view, name='otch_all_reelt'),
    url(r'^sdelka/(?P<idd>[0-9]+)/$', views.reelt_sdelka_otchet_detail_view, name='otch_detail'),
    url(r'^sdelka/zakrit/(?P<idd>[0-9]+)/$',views.sdelka_zakritie_view, name='sdelka_zakr'),
    url(r'^sdelka/sriv/(?P<idd>[0-9]+)/$',views.sdelka_sriv_view, name='sdelka_sriv'),
    url(r'^sdelka/rasr/(?P<idd>[0-9]+)/$',views.sdelka_rasroch_view, name='sdelka_rasr'),
    url(r'^sdelka/delete/(?P<idd>[0-9]+)/$',views.sdelka_delete_view, name='sdelka_del'),
    url(r'^totchet/$', views.tempFioView,name='1'),#all fio in sdelka edit
    url(r'^testotch/$',views.kach_otch_view,name='DmCahestvoOtch'), #temp for domck kachestvo
    url(r'^perenos_groups/$',views.temp_otch_view, name='tempGroupOtchet'), #for perenos groups

    # feeds
    url(r'^cian.xml$', views.cianfeedview, name='cian'),
    url(r'^ncian.xml$', views.cianfeedview1, name='cian'),#new cian feed
    url(r'^megareal.xml$', views.MegaRealfeedview, name='mega'),
    url(r'^new/$',views.newvigrView, name='newvigr'),
    url(r'^nnew/$',views.newvigrNovostroikaView , name='newNovvigr'),
    url(r'^newviggal/(?P<idd>[0-9]+)/$',views.newVigGalView, name='newvigrgal'),
    url(r'^cianindex/$', views.cianindexview, name='cianindex'),
    url(r'^cianindexup/$', views.cianindexUPview, name='cianindexupl'),
    url(r'^cianedit/(?P<idd>[0-9]+)/$',views.cianedit, name='cianedit'),
    url(r'^ciandels/(?P<idd>[0-9]+)/$',views.cianDelviewSubjct, name='ciandelsubj'),
    url(r'^ciandel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.ciandelview, name='ciandel'),

    #Zayavki
    url(r'^zayavka/new/$',views.New_Zayavka_View, name='NewZayav'),
    url(r'^zayavka/new_nov/$', views.New_Nov_Zayavka_View, name='NewZayavNov'),
    url(r'^zayavka/new_nov_lich/$', views.lich_rielt_Zayavka_View, name='NewZayavLich'),
    url(r'^index/$',views.zaiyavka_Index_view, name='indexZayavka'),
    url(r'^zayavka/vzyat/(?P<idd>[0-9]+)/$', views.zayavka_vzyata_view, name='VzyatZayav'),
    url(r'^zayavka/sdelka/(?P<idd>[0-9]+)/$', views.zayavka_sdelka_view, name='SdelkaZayav'),
    url(r'^zayavka/sriv/(?P<idd>[0-9]+)/$', views.zayavka_sriv_view, name='SdelkaSriv'),

    #statistika
    url(r'^stat_obj/$', views.stat_count_crm_obj, name='crm_obj_index'),
    url(r'^stat_obj_past/$', views.stat_count_crm_obj_past, name='crm_obj_past_index'),
    url(r'^stat_obj_adler/$', views.stat_count_crm_obj_adler, name='crm_obj_index_adler'),
    url(r'^stat_obj_past_adler/$', views.stat_count_crm_obj_past_adler, name='crm_obj_past_index_adler'),
    url(r'^sdelkaReiting/(?P<year_pr>[0-9]+)/$', views.new_reyting_po_sdelkam,
        name='New_Sdelka_Reit'),
    url(r'^stat_obj/report_in_otdel/(?P<group_pk>[0-9]+)/$', views.ReportInOtdelView, name='report_in_otdel_html'),#
    url(r'^stat_obj/report_in_otdel/all/$', views.ReportAllRieltsView, name='report_all_html'),
    url(r'^stat_obj/report_in_otdel/otdels/$', views.ReportOtdelsView, name='report_otdels_html'),
    url(r'^stat_obj/report_in_otdel/agent/(?P<agent_id>[0-9]+)/$', views.ReportAgentObjectsView, name='agent_report_in_otdel_html'),

    #for homka admin
    url(r'^myadm/$', views.my_admi_view, name = 'myadm'),
    url(r'^myadm/usrbals/(?P<idd>[0-9]+)/$',views.UserBallsAddView, name='usrbalsadd'),
    url(r'^myadm/agent_id/(?P<agent_id>[\w\-]+)/$', views.AgentObjectsView, name='agent_id_url'),
    url(r'^myadm/admin/agent_id/(?P<agent_id>[\w\-]+)/$', views.AdminAgentObjectsView, name='admin_agent_id_url'),
    url(r'^myadm/user_edit/(?P<agent_id>[\w\-]+)/$', views.UserEditView, name='user_edit_url'),
    url(r'^myadm/user_new/$', views.UserNewView, name='user_new_url'),

    # Phone Calls Views
    url(r'^myadm/admin_phone_calls/$', views.AdminPhoneView, name='adm_phone_call'),
    url(r'^myadm/department_phone_calls/(?P<idd>[\w\-]+)/$', views.DepatmentPhoneView, name='department_phone_call'),
    url(r'^myadm/user_phone_calls/(?P<idd>[\w\-]+)/$', views.UserPhoneView, name='user_phone_call'),

    # for Dashboard
    url(r'^dashboard/$', views.DashBoardView, name='DashBoard'),

    #Domcklic texts
    url(r'^dm/index/$', views.dmIndexView, name='dm_index'),
    url(r'^dm/edit/(?P<idd>[0-9]+)/$', views.EditDMtextView, name='dm_edit'),

templates/any/GRFeed.html
<realty-feed xmlns="http://webmaster.yandex.ru/schemas/feed/realty/2010-06">
 <generation-date>{{ tdate|date:"Y-m-d"  }}T{{ tdate|date:"h:m:s" }}+03:00</generation-date>
 {% for post in tppost %}
 <offer internal-id="{{ post.pk }}">
    <type>Продажа</type>
    <category>квартира</category>
    <property-type>Жилая</property-type>
 <creation-date>{{ post.datep|date:"Y-m-d" }}T01:11:30+03:00</creation-date>
 <last-update-date>{{ tdate|date:"Y-m-d"  }}T{{ tdate|date:"h:m:s" }}+03:00</last-update-date>
 <location>
    <country>Россия</country>
    <region>Краснодарский край</region>
    <locality-name>Сочи</locality-name>
    <address>{{ post.adress }} {{ post.dom_numb }} {{ post.kvart_numb }}</address>
</location>
<sales-agent>
    <phone>{{ post.author.userprofile1.tel }}</phone>
    <name>{{  post.author.first_name }} {{ post.author.last_name }}</name>
    <email>{{ post.author.email }}</email>
</sales-agent>
<price>
    <value>{{ post.cena_agenstv }}</value>
    <currency>RUR</currency>
</price>
    <deal-status>прямая продажа</deal-status>
    <description>{{ post.prim }}  {{ tdm }}
</description>

{% for i in post.idd_gal.all %}
    {% if i.npict.url %}
    <image>
      http://77.222.52.20{{ i.npict.url }}
    </image>
    {% endif %}
{% endfor %}

<area>
    <value>{{ post.ploshad }}</value>
    <unit>кв.м</unit>
</area>

<living-space>
    <value>{{ post.ploshad }}</value>
    <unit>кв.м</unit>
</living-space>

<kitchen-space>
    {% if post.ploshad <= 20 %}
        <value>2</value>
    {% endif %}
    {% if post.ploshad > 20 and post.ploshad <= 40 %}
        <value>4</value>
    {% endif %}
    {% if post.ploshad > 40 and post.ploshad <= 60 %}
        <value>5</value>
    {% endif %}
    {% if post.ploshad > 60 and post.ploshad <= 80 %}
        <value>10</value>
    {% endif %}
    {% if post.ploshad > 80 %}
        <value>15</value>
    {% endif %}
    <unit>кв.м</unit>
</kitchen-space>

<gas-supply>
    {% if post.gaz == 'Есть' %}
        да
    {% else %}
        нет
    {% endif %}
</gas-supply>
<bathroom-unit>
    {%  if post.san_usel == 'Совмещенный' %}
        совмещенный
    {% endif %}
    {%  if post.san_usel == 'Раздельный' %}
        раздельный
    {% endif %}
</bathroom-unit>
<renovation>
    {% if post.remont == 'Черновой' %}черновая отделка{% endif %}
    {% if post.remont == 'Чистовой' %}с отделкой{% endif %}
    {% if post.remont == 'Дизайнерский' %}дизайнерский{% endif %}
    {% if post.remont == 'Жилой' %}евро{% endif %}
    {% if post.remont == 'Новый' %}хороший{% endif %}
</renovation>
    {% if post.komnat == 'Студия' %}
        <rooms>1</rooms>
    {% endif %}
    {% if post.komnat == 'Однокомнатная' %}
        <rooms>1</rooms>
    {% endif %}
    {% if post.komnat == 'Двухкомнатная' %}
        <rooms>2</rooms>
    {% endif %}
    {% if post.komnat == 'Трехкомнатная' %}
        <rooms>3</rooms>
    {% endif %}
    {% if post.komnat == 'Многокомнатная' %}
        <rooms>4</rooms>
    {% endif %}
    <floor>{{ post.etag }}</floor>
    <floors-total>{{ post.etagnost }}</floors-total>

 </offer>
 {% endfor %}


{% if tdom %}
    {% for doma in tdom %}
    <offer internal-id="{{ doma.pk }}">
    <type>Продажа</type>
    <property-type>Жилая</property-type>
    <category>дом</category>
 <creation-date>{{ doma.datep|date:"Y-m-d" }}T01:11:30+03:00</creation-date>
 <last-update-date>{{ tdate|date:"Y-m-d"  }}T{{ tdate|date:"h:m:s" }}+03:00</last-update-date>
 <location>
    <country>Россия</country>
    <region>Краснодарский край</region>
    <locality-name>Сочи</locality-name>
    <address>{{ doma.adress }}</address>
</location>
<sales-agent>
    <phone>{{ doma.author.userprofile1.tel }}</phone>
    <name>{{  doma.author.first_name }} {{ doma.author.last_name }}</name>
    <email>{{ doma.author.email }}</email>
</sales-agent>
<price>
  <value>{{ doma.cena_agenstv }}</value>
  <currency>RUR</currency>
</price>
<description>{{ doma.prim }}</description>
<area>
  <value>{{ doma.ploshad }}</value>
  <unit>кв. м</unit>
</area>
<lot-area>
  <value>{{ doma.h_ploshad_uch }}</value>
  <unit>кв. м</unit>
</lot-area>
{%  if doma.h_tip_doma_choises == 'Монолитный' %}
    <building-type>монолит</building-type>
{% endif %}
{%  if doma.h_tip_doma_choises == 'Блочный' %}
    <building-type>блочный</building-type>
{% endif %}
{%  if doma.h_tip_doma_choises == 'Каркасно-монолитный' %}
    <building-type>кирпично-монолитный</building-type>
{% endif %}
{%  if doma.h_tip_doma_choises == 'Кирпичный' %}
    <building-type>кирпичный</building-type>
{% endif %}
{%  if doma.h_tip_doma_choises == 'Деревянный' %}
    <building-type>деревянный</building-type>
{% endif %}
{%  if doma.h_tip_doma_choises == 'Панельный' %}
    <building-type>панельный</building-type>
{% endif %}
{%  if doma.h_vid_prava  == 'Поселений (ИЖС)'%}
<lot-type>ИЖС</lot-type>
{% else %}
<lot-type>садоводство</lot-type>
{% endif %}
<floors-total>{{ doma.h_etagnost }}</floors-total>
<rooms>{{ doma.h_komnat }}</rooms>

{% for i in doma.idd_gal.all %}
   {% if i.npict.url %}
    <image>
      http://77.222.52.20{{ i.npict.url }}
    </image>
   {% endif %}
{% endfor %}

        </offer>

    {% endfor %}
{% endif %}
</realty-feed>

templates/any/domclick.html
<feed>
  <feed_version>2</feed_version>
    {% for post in tppost %}
  <object>
    <Category>flatSale</Category>
    <ExternalId>{{ post.pk }}</ExternalId>
    <RoomType>both</RoomType>
    <Description>{{ post.prim }}</Description>
    <Address>{% if post.kr_raion == '' %}Сочи{% else %}Краснодар{% endif %}, {{ post.adress }} {{ post.dom_numb }} {{ post.kvart_numb }}</Address>
    <FlatRoomsCount>{{ post.komnat }}</FlatRoomsCount>
        <Phones>
      <PhoneSchema>
        <CountryCode>+7</CountryCode>
        <Number>{{ post.author.userprofile1.tel  }}</Number>
      </PhoneSchema>
      <PhoneSchema>
        <CountryCode>+7</CountryCode>
        <Number>{{ post.author.userprofile1.tel  }}</Number>
      </PhoneSchema>
    </Phones>
    <TotalArea>{{ post.ploshad }}</TotalArea>
    <FloorNumber>{{ post.etag }}</FloorNumber>
    <SubAgent>
      <Email>{{ post.author.email }}</Email>
      <Phone>+7{{ post.author.userprofile1.tel  }}</Phone>
      <FirstName>{{  post.author.first_name }}</FirstName>
      <LastName>{{ post.author.last_name }}</LastName>
    </SubAgent>
    <Photos>
	{% for i in post.idd_gal.all %}
      <PhotoSchema>
        <FullUrl>http://35.195.61.28{{ i.npict.url }}</FullUrl>

      </PhotoSchema>
        {% endfor %}
    </Photos>
    <Building>
        <FloorsCount>{{ post.etagnost }}</FloorsCount>
    </Building>
    <BargainTerms>
      <Price>{{ post.cena_agenstv }}</Price>
      <Currency>rur </Currency>
    </BargainTerms>
  </object>
{% endfor %}

</feed>

templates/any/flatgalform.html
{% extends 'crm/main.html' %}
{% block content %}
{% load i18n staticfiles %}
{% load material_form %}
    <div class="row">
         <div class="col s12">
            <div class="card">
                <div class="card-content">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                Выберите не менее 5 картинок<strong> (Нажав кнопку ctr можно выбрать сразу несколько файлов!)</strong>
            </p>
            <input type="file" name="myfiles" multiple>
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        </form>
                </div>
            </div>
             <div class="card">
                <div class="card-content">
                    <div class="card-content">

        <table class="bordered">
   {% if post.idd_gal.all %}

    {% for i in post.idd_gal.all %}
        <tbody>
          <tr>
            <td> ID: {{ i.pk }}  </td>
            <td><a href="{{MEDIA_ROOT}}{{ i.npict.url }}"><img src="{{MEDIA_ROOT}}{{ i.npict.url }}"  height="232"></a>  </td>
            <td><a href="{% url 'crm:my_flatpub'  %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Закончить редактирование</button></a></td>
            <td><a href="{% url 'crm:FlatPhotodel' idd=post.pk sidd=i.pk %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Удалить</button></a></td>
          </tr>

        </tbody>


    {% endfor %}
    {% endif%}

                </div>
            </div>
         </div>
     </div>





{% endblock %}

templates/any/newotchet.html
{% extends 'crm/main.html' %}
{% block content %}

{% load material_form %}
    <div class="row">
         <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form method="post" class="post-form">
                    {% csrf_token %}
                        {% form form=tpotchformall layout=form.layout%}{% endform %}
                        <button type="submit" name="_submit" class="btn">{{ tsave }}</button>
                    {% if tgroup == 'Администрация' or tgroup == 'Администрация Адлер'  %}
                       <a href="{% url 'crm:sdelka_sriv' idd=tid %}" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Срыв сделки</a>
                    {% if tRasrPr == 'No_rasr' %}
                        <a href="{% url 'crm:sdelka_rasr' idd=tid %}" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Расрочка</a>
                     {% endif %}
                       <a href="{% url 'crm:sdelka_del' idd=tid %}" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Удалить отчет</a>
                    {% endif %}</form>
                </div>
            </div>



         </div>
     </div>
{% endblock %}

templates/any/userballadd.html
{% extends 'crm/main.html' %}
{% block content %}
<style>.ml-1.d-none.d-sm-block {
    display: none !important;
}</style>
<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-body">
    <blockquote>{{ tusr.first_name }} {{ tusr.last_name }} {{ tusr.groups.all.0 }}</blockquote>
    {% load material_form %}
    <form method="post" class="post-form">
    {% csrf_token %}
    {% form form=tform %}{% endform %}
    <button type="submit"  name="balls_add" class="btn">Сохранить</button>
    </form>
</div>
</div>
</div>
</div>
{% endblock %}

templates/any/vigGalForm.html
{% extends 'crm/main.html' %}
{% block content %}

{% load material_form %}
    <div class="row">
         <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form enctype="multipart/form-data" method="post" class="post-form">
                    {% csrf_token %}
                        {% form form=tpform layout=form.layout%}{% endform %}
                        <button type="submit" name="_submit" class="btn">Сохранить и добавить фото</button>
</form>

                </div>
            </div>
             <div class="card">
                <div class="card-content">
                    <div class="card-content">

        <table class="bordered">
   {% if post.idd_gal.all %}

    {% for i in post.idd_gal.all %}
        <tbody>
          <tr>
            <td> ID: {{ i.pk }}  </td>
            <td><a href="{{MEDIA_ROOT}}{{ i.npict.url }}"><img src="{{MEDIA_ROOT}}{{ i.npict.url }}"  height="232"></a>  </td>
            <td><a href="{% url 'crm:cianindex'  %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Закончить редактирование</button></a></td>
            <td><a href="{% url 'crm:ciandel' idd=post.pk sidd=i.pk %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Удалить</button></a></td>
          </tr>

        </tbody>


    {% endfor %}
    {% endif%}

                </div>
            </div>
         </div>
     </div>





{% endblock %}

templates/any/vigrform.html
{% extends 'crm/main.html' %}
{% block content %}

{% load material_form %}
    <div class="row">
         <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form method="post" class="post-form">
                    {% csrf_token %}
                        {% form form=tpform layout=form.layout%}{% endform %}
                        <button type="submit" name="_submit" class="btn">Сохранить и добавить фото</button>
                </div>
            </div>
         </div>
     </div>

</form>






{% endblock %}