crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.http import request
#from django.views.generic import DetailView,ListView

from . import views


app_name='crm'

urlpatterns = [
    #login
    url(r'^$', views.login_view,  name='login'),
    url(r'^logout/', views.logoutview, name='logout'),



    #news
    url(r'^news/$', views.DashBoardView, name='news_index'),
    #url(r'^news/$', views.zaiyavka_Index_view, name='news_index'),
    url(r'^news/(?P<idd>[0-9]+)/$',views.news_detail_view, name='news_detail'),
    url(r'^news/edit(?P<idd>[0-9]+)/$', views.news_edit_view, name='news_edit'),
    url(r'^news/newnews/$', views.news_postform, name='news_newpost'),

    #flats
    url(r'^flats/newflat/$', views.flat_postForm, name='new_flat'),
    url(r'^flats/newflat_appart/$', views.flat_apparts_postForm, name='flat_apparts_postForm'),#new flat(only for appartaments)
    url(r'^flats/myflats_pub/$', views.my_flatview_pub, name='my_flatpub'), ## All Flats
    url(r'^flats/excl_flats_pub/$', views.excl_flatview_pub, name='excl_flatpub'), ## Exclusive Flats
    url(r'^flats/allflats_pub/$', views.all_flatview_pub, name='all_flatpub'),

    url(r'^flats/vestum/pup/(?P<idd>[0-9]+)/$',views.vestum_pub_view, name='Vs_pub'),
    url(r'^flats/all_vs_pub/$', views.vestum_All_pub_view, name = 'all_vs_pub'),

    url(r'^flats/Seo_flats_pub/$', views.all_flatviewSeo_pub, name='seo_flat_pub'),
    url(r'^flats/Seo_flats_Unpub/$', views.all_flatviewSeo_unpub, name='seo_flat_unpub'),
    url(r'^flats/allflats_pub_form/(?P<idd>[0-9]+)/$', views.seo_flat_pub, name='form_flatpub'),

    url(r'^flats/myflats_unpub/$', views.my_flatview_unpub, name='my_flatunpub'),
    url(r'^flat/edit(?P<idd>[0-9]+)/$', views.my_flatview_edit, name='flat_edit'),
    url(r'^flat/(?P<idd>[0-9]+)/$', views.myflatDetail, name='flat_detail'),
    url(r'^flat/print/(?P<idd>[0-9]+)/$', views.myflatPrint, name='flat_print'),
    url(r'^newFlatGal/(?P<idd>[0-9]+)/$',views.flat_photo_new_view, name='newFlatgal'),
    url(r'^flatdel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.flat_del_view, name='FlatPhotodel'),
    url(r'^flat_rotate/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.FlatPctRotateView, name='FlatPctRotate'),
    ##feeds
    url(r'^domclick.xml$', views.YandexFeedview, name='Yandex'),#for yandex feed
    url(r'^mail.xml$', views.MailRuFeedview, name='Mail'),  # for mail.ru feed
    url(r'^grFeed.xml$', views.GRFeedview, name='Yandex'),  # for yandex feed
    url(r'^domclick1.xml$', views.domclickfeedview, name='domclick'), #for domclick
    url(r'^vestum.xml$', views.vestumfeedview, name='vestumFeed'), #for Vestum 700
    url(r'^vestum300.xml$', views.vestumfeedview300, name='vestumFeed300'),  # for Vestum 300
    url(r'^vestumHouses.xml$', views.vestumFeedViewHouses, name='vestumHouses'),  # for Vestum Houses
    url(r'^sait.xml$', views.sait_vigr_view, name='domclick'), #for sait_feed
    url(r'^newyandex.xml$', views.NewYandexFeedview, name='NewYandex'),  # for New yandex feed(no Fakes)
    url(r'^newsait21.xml$', views.NewSaitFeedview, name='NewSait'),  # for New Sait(21 centry) feed(no Fakes)
    url(r'^afy.xml$', views.AfyFeedview, name='Afy'),  # for New yandex feed(no Fakes)
    ##any
    url(r'^domclick_index/$', views.domclick_Index_view, name='domclick_index'),
    url(r'^kdastr/(?P<idd>[0-9]+)/$', views.kadastr_edit, name='new_kadastr'),# new_kadastr_numb

    #clients
    url(r'^clients/newclient/$', views.new_client_view, name='new_client'),
    url(r'^clients/editclient/(?P<idd>[0-9]+)/$', views.edit_client_view, name='edit_client'),
    url(r'^clients/own_clients/$', views.own_clients_view, name='own_clienws'),
    url(r'^clients/all_clients/$', views.all_clients_view, name='all_clienws'),
    url(r'^clients/otd_clients/$', views.otd_clients_view, name='otd_clienws'),
    url(r'^client/(?P<idd>[0-9]+)/$', views.cliend_detail_view, name='client_detail'),

    #doma
    url(r'^new_dom/$', views.new_dom_view, name='new_dom_post'),
    url(r'^pub_unp_dom/$', views.mu_unpob_doma_view, name='upb_dom_view'),
    url(r'^pub_pub_dom/$', views.mu_pob_doma_view, name='pub_dom_view'),
    url(r'^doms/(?P<idd>[0-9]+)/$',views.dom_detail_view,name='dom_detail'),
    url(r'^doms/edit(?P<idd>[0-9]+)/$', views.domaeditview, name='dom_edit'),
    url(r'^doms/print/(?P<idd>[0-9]+)/$',views.dom_print_view,name='dom_print'),
    url(r'^doms/pct_del/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.house_del_view,name='dom_pct_del'),

    #uchastki
    url(r'^new_uch/$', views.new_uc_view, name='new_uch_post'),
    url(r'^pub_uch/$',views.pup_uchastki,name='pub_uc_index'),
    url(r'^un_uch/$',views.unpup_uchastki,name='unpub_uc_index'),
    url(r'^uch/(?P<idd>[0-9]+)/$',views.uch_detail_view,name='uc_detail'),
    url(r'^uchprt/(?P<idd>[0-9]+)/$',views.uch_print_view,name='uc_print'),
    url(r'^uch/edit(?P<idd>[0-9]+)/$', views.ucheditview, name='uc_edit'),
    url(r'^uch/delete/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$', views.uchastok_del_view, name='uc_delete'),

    #Commerce
    url(r'^commerce/new$', views.NewCommerceView, name='new_commerce_url'),
    url(r'^commerce/my/index$', views.MyIndexCommerceView, name='my_index_commerce_url'),
    url(r'^commerce/all/index$', views.AllIndexCommerceView, name='all_index_commerce_url'),
    url(r'^commerce/detail/(?P<idd>[0-9]+)$', views.DetailCommerceView, name='detail_commerce_url'),
    url(r'^commerce/edit/(?P<idd>[0-9]+)$', views.EditCommerceView, name='edit_commerce_url'),

    #otchet
    url(r'^newotchet/$',views.new_otchet_view_All, name='otch_new_all'),
    url(r'^editotchet/(?P<idd>[0-9]+)/$', views.otchet_edit_view, name='otch_edit'),
    url(r'^allochet(?P<tpr_tab>[0-9]+)/$',views.reeelt_otchet_all_view, name='otch_all_reelt'),
    url(r'^sdelka/(?P<idd>[0-9]+)/$', views.reelt_sdelka_otchet_detail_view, name='otch_detail'),
    url(r'^sdelka/zakrit/(?P<idd>[0-9]+)/$',views.sdelka_zakritie_view, name='sdelka_zakr'),
    url(r'^sdelka/sriv/(?P<idd>[0-9]+)/$',views.sdelka_sriv_view, name='sdelka_sriv'),
    url(r'^sdelka/rasr/(?P<idd>[0-9]+)/$',views.sdelka_rasroch_view, name='sdelka_rasr'),
    url(r'^sdelka/delete/(?P<idd>[0-9]+)/$',views.sdelka_delete_view, name='sdelka_del'),
    url(r'^totchet/$', views.tempFioView,name='1'),#all fio in sdelka edit
    url(r'^testotch/$',views.kach_otch_view,name='DmCahestvoOtch'), #temp for domck kachestvo
    url(r'^perenos_groups/$',views.temp_otch_view, name='tempGroupOtchet'), #for perenos groups

    # feeds
    url(r'^cian.xml$', views.cianfeedview, name='cian'),
    url(r'^ncian.xml$', views.cianfeedview1, name='cian'),#new cian feed
    url(r'^megareal.xml$', views.MegaRealfeedview, name='mega'),
    url(r'^new/$',views.newvigrView, name='newvigr'),
    url(r'^nnew/$',views.newvigrNovostroikaView , name='newNovvigr'),
    url(r'^newviggal/(?P<idd>[0-9]+)/$',views.newVigGalView, name='newvigrgal'),
    url(r'^cianindex/$', views.cianindexview, name='cianindex'),
    url(r'^cianindexup/$', views.cianindexUPview, name='cianindexupl'),
    url(r'^cianedit/(?P<idd>[0-9]+)/$',views.cianedit, name='cianedit'),
    url(r'^ciandels/(?P<idd>[0-9]+)/$',views.cianDelviewSubjct, name='ciandelsubj'),
    url(r'^ciandel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.ciandelview, name='ciandel'),

    #Zayavki
    url(r'^zayavka/new/$',views.New_Zayavka_View, name='NewZayav'),
    url(r'^zayavka/new_nov/$', views.New_Nov_Zayavka_View, name='NewZayavNov'),
    url(r'^zayavka/new_nov_lich/$', views.lich_rielt_Zayavka_View, name='NewZayavLich'),
    url(r'^index/$',views.zaiyavka_Index_view, name='indexZayavka'),
    url(r'^zayavka/vzyat/(?P<idd>[0-9]+)/$', views.zayavka_vzyata_view, name='VzyatZayav'),
    url(r'^zayavka/sdelka/(?P<idd>[0-9]+)/$', views.zayavka_sdelka_view, name='SdelkaZayav'),
    url(r'^zayavka/sriv/(?P<idd>[0-9]+)/$', views.zayavka_sriv_view, name='SdelkaSriv'),

    #statistika
    url(r'^stat_obj/$', views.stat_count_crm_obj, name='crm_obj_index'),
    url(r'^stat_obj_past/$', views.stat_count_crm_obj_past, name='crm_obj_past_index'),
    url(r'^stat_obj_adler/$', views.stat_count_crm_obj_adler, name='crm_obj_index_adler'),
    url(r'^stat_obj_past_adler/$', views.stat_count_crm_obj_past_adler, name='crm_obj_past_index_adler'),
    url(r'^sdelkaReiting/(?P<year_pr>[0-9]+)/$', views.new_reyting_po_sdelkam,
        name='New_Sdelka_Reit'),
    url(r'^stat_obj/report_in_otdel/(?P<group_pk>[0-9]+)/$', views.ReportInOtdelView, name='report_in_otdel_html'),#
    url(r'^stat_obj/report_in_otdel/all/$', views.ReportAllRieltsView, name='report_all_html'),
    url(r'^stat_obj/report_in_otdel/otdels/$', views.ReportOtdelsView, name='report_otdels_html'),
    url(r'^stat_obj/report_in_otdel/agent/(?P<agent_id>[0-9]+)/$', views.ReportAgentObjectsView, name='agent_report_in_otdel_html'),

    #for homka admin
    url(r'^myadm/$', views.my_admi_view, name = 'myadm'),
    url(r'^myadm/usrbals/(?P<idd>[0-9]+)/$',views.UserBallsAddView, name='usrbalsadd'),
    url(r'^myadm/agent_id/(?P<agent_id>[\w\-]+)/$', views.AgentObjectsView, name='agent_id_url'),
    url(r'^myadm/admin/agent_id/(?P<agent_id>[\w\-]+)/$', views.AdminAgentObjectsView, name='admin_agent_id_url'),
    url(r'^myadm/user_edit/(?P<agent_id>[\w\-]+)/$', views.UserEditView, name='user_edit_url'),
    url(r'^myadm/user_new/$', views.UserNewView, name='user_new_url'),

    # Phone Calls Views
    url(r'^myadm/admin_phone_calls/$', views.AdminPhoneView, name='adm_phone_call'),
    url(r'^myadm/department_phone_calls/(?P<idd>[\w\-]+)/$', views.DepatmentPhoneView, name='department_phone_call'),
    url(r'^myadm/user_phone_calls/(?P<idd>[\w\-]+)/$', views.UserPhoneView, name='user_phone_call'),

    # for Dashboard
    url(r'^dashboard/$', views.DashBoardView, name='DashBoard'),

    #Domcklic texts
    url(r'^dm/index/$', views.dmIndexView, name='dm_index'),
    url(r'^dm/edit/(?P<idd>[0-9]+)/$', views.EditDMtextView, name='dm_edit'),

templates/crm/flat/all_flat_index.html
{% extends 'crm/main.html' %}
{% block content %}
{{ tpaFlatSearch.media.css }}
<style type="text/css">
        input, select,select2 select2-container {width: 100%}
</style>
    <script src="/static/select/jquery-3.4.1.js"></script>


<div class="row">
<div class="col-lg-12">
<form method="post" class="post-form"> {% csrf_token %}
{#    <p> {{ tpaFlatSearch.search_raion }}</p>#}
    <div class="row">
      <div class="col s1">{{ tpaFlatSearch.search_raion.label }} {{ tpaFlatSearch.search_raion }}</div>
      <div class="col s1">{{  tpaFlatSearch.contract.label }} {{  tpaFlatSearch.contract }}</div>
    </div>
    <div class="row">
      <div class="col s1">{{ tpaFlatSearch.search_minp.label }} {{ tpaFlatSearch.search_minp }}</div>
      <div class="col s1">{{ tpaFlatSearch.search_maxp.label }} {{ tpaFlatSearch.search_maxp }}</div>
    </div>
        <div class="row">
      <div class="col s1">{{ tpaFlatSearch.search_minc.label }} {{ tpaFlatSearch.search_minc }}</div>
      <div class="col s1">{{ tpaFlatSearch.search_maxc.label }} {{ tpaFlatSearch.search_maxc }}</div>
    </div>

<button type="submit" name="_submit" class="btn">Найти</button>
</form></div>
   <div class="col-lg-12">
      <div class="card">
         <div class="card-content">
            {% load material_form %}
            <table class="bordered">
               <thead>
                  <tr>
                      <th>ID</th>
                     <th></th>
                      <th>Kоличество комнат</th>
                     <th>Oтветственный</th>
                     <th>Цена</th>
                     <th>Район</th>
                     <th>Адрес</th>
                     <th></th>
                     {% comment %}{% ifequal request.user.userprofile1.ya "Да" %}
                     <th>Статус</th>
                     {% endifequal%} {% endcomment %}
                  </tr>
               </thead>
               {% if tpflatlist %}
               {% load el_pagination_tags %}
               {% lazy_paginate  tpflatlist %}
               {% for flatlist in tpflatlist %}
               <tbody>
                <td>{{ flatlist.pk }}</td>
                    <td>
              {% if flatlist.main_pct %}
                   <img
                                                        class="materialboxed"
                                                        rel="gallery"
                                                        height="100"
                                                        src="http://77.222.52.20{{ flatlist.main_pct.url }}"></div>
               {% else %}
                        {% for i in flatlist.idd_gal.all|slice:":1" %}
                            <img
                                                        class="materialboxed"
                                                        rel="gallery"
                                                        height="100"
                                                        src="http://77.222.52.20{{ i.npict.url }}"></div>
                        {% endfor %}
                    </td>
                {% endif %}
                     {%  if request.user.groups.get.name == 'Офис-менеджер' %}
                     <td> <a href="{% url 'crm:new_kadastr' idd=flatlist.pk %}">{{ flatlist.date_sozd }}</a> </td>
                     {% else %}
                     <td> {{ flatlist.komnat }}{% comment %}{{ flatlist.date_sozd }}({{ flatlist.status_obj }}){% endcomment %} </td>
                     {% endif %}
                     <td> {{ flatlist.author.first_name }} {{ flatlist.author.last_name }}{% comment %}{ flatlist.pk }}{% endcomment %}</td>
                     <td> {{ flatlist.cena_agenstv }} </td>
                     <td> {{ flatlist.raion }} {{ flatlist.kr_raion }}</td>
                     <td>{{ flatlist.adress }} {{ flatlist.dom_numb }}</td>
                     {% comment %}
                     <td>
                        {%  ifequal request.user flatlist.author %}
                        {%  ifequal flatlist.text_err True %} Текст; {% endifequal %}
                        {%  ifequal flatlist.kv_err True %} №кв/кадстр; {% endifequal %}
                        {%  ifequal flatlist.dom_err True %} № Дома; {% endifequal %}
                        {%  ifequal flatlist.pict_err True %} Карт; {% endifequal %}
                        {% endifequal %}
                     </td>
                     <td>
                        {% ifequal request.user flatlist.author%}
                        {% comment %} {% if flatlist.vestum_pub == 'Да' %}<i class="material-icons" >V+</i>{% endif %}
                        {% if flatlist.kadastr != '' %}<i class="material-icons" >K+</i>{% endif %}
                        {% if flatlist.domclick_pub == 'Да' and flatlist.kadastr != '' %}<i class="material-icons" >Дм+</i>{% endif %}
                        {% endifequal %}
                     </td>
                     {% ifequal request.user.userprofile1.ya "Да" %}
                     {% ifequal request.user flatlist.author%}
                     <td> {{ flatlist.building_name }}</td>
                     {% endifequal %}
                     {% endifequal%}{% endcomment %}
                     <td><a href="{% url 'crm:flat_detail' idd=flatlist.pk %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Подробнее</button></a></td>
                  </tr>
               </tbody>
               {% endfor %}
            </table>
            {% get_pages %}
            <ul class="pagination">
               {% for page in pages %}
               <li>
                  <a href="{{ page.path }}" rel="page" class="endless_page_link">{{ page.number }}</a>
               </li>
               {% endfor %}
            </ul>
            {% else %}
            </tbody></br></br></br>
            <strong>У Вас пока нет обьектов</strong>
            {% endif %}
            </tbody>
            </table>
         </div>
      </div>
   </div>
    {% comment %}
   <div class="col-lg-3">
      {% if kr_flag == 'Yes' %}
      <div class="card">
         <div class="card-content">
            <form method="post" class="post-form">
               <h2>Сочи</h2>
               {% csrf_token %}
               {% form form=KrFlatSearch %} {% endform %}
               <button type="submit" name="_kr_submit" class="btn">Найти</button>
            </form>
         </div>
      </div>
   {% endif %}
      <div class="card">
         <div class="card-content">
            <form method="post" class="post-form">
               <h2>Сочи</h2>
               {% csrf_token %}
               {% form form=tpaFlatSearch %} {% endform %}
               <button type="submit" name="_submit" class="btn">Найти</button>
            </form>
         </div>
      </div>
   </div>

</div>{% endcomment %}
<!--
   <div class="fixed-action-btn horizontal">
   <a class="btn-floating btn-large red">
     <i class="large material-icons">access_time</i>
   </a>

   <ul>
     <li><a href="{% url 'crm:my_flatunpub' %}" class="btn-floating yellow darken-1"title = "Личные"><i class="material-icons">account_box</i></a></li>
     <li><a <a href="{% url 'crm:my_flatpub' %}"  class="btn-floating green" title = "В агенстве"><i class="material-icons">announcement</i></a></li>
   -->
</ul>
    </div>

        {{ tpaFlatSearch.media.js }}
<script src="/static/select/js/i18n/ru.js"></script>


{% endblock %}

templates/crm/flat/flat_search.html
{% extends 'crm/main.html' %}
{% block content %}


    {# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<form method="post" class="post-form">
  {% csrf_token %}
  {% bootstrap_form tpform %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">{% bootstrap_icon "floppy-saved" %} Сохранить</button>

  {% endbuttons %}
</form>






{% endblock %}

templates/crm/flat/flatedit.html
{% extends 'crm/main.html' %}
{% block content %}
{% load material_form %}
<div class="row">
   <div class="col s12">
      <div class="card">
         <div class="card-content">
            {{ tadr }}
            <form enctype="multipart/form-data" method="post" class="post-form">
               {% csrf_token %}
               {% form form=tpflatpostform layout=form.layout%}{% endform %}{{ tdate }}
               <ul class="collapsible">
                  <li>
                      <div class="collapsible-header"><i class="material-icons"></i>{{ post.contract}} <strong>(Договор)</strong></div>
                     <div class="collapsible-body">
                        <span>
                           <select name="compo" >
                              <option></option>
                              <option {% if post.contract == 'Без договора' %} selected {% endif %} >Без договора</option>
                              <option {% if post.contract == 'Агентский' %} selected {% endif %} >Агентский</option>
                              <option {% if post.contract == 'Эксклюзив' %} selected {% endif %} >Эксклюзив</option>
                           </select>
                           <input type="date" name="date" value="{{ post.contract_date_end|date:'Y-m-d' }}"> Дата окончания {{ post.contract_date_end|date:'Y-m-d' }}
                           <input type="text" name="contract_number" value="{{ post.contract_number }}"> Номер договора
                           </p>
                        </span>
                     </div>
                  </li>
               </ul>
    {% if post.main_pct %}
        <tbody>
          <tr>
            <td>  </td>
            <td><a href="{{ MEDIA_ROOT }}{{ post.main_pct.url }}"><img src="{{MEDIA_ROOT}}{{ post.main_pct.url }}"  height="232"></a>  </td>
              <td></td>
              <td></td>
          </tr>
        </tbody>
    {% endif %}

    {% if post.idd_gal.all %}
        {% for i in post.idd_gal.all %}
        <tbody>
          <tr>
            <td> ID: {{ i.pk }}  </td>
            <td><a href="{{ MEDIA_ROOT }}{{ i.npict.url }}"><img src="{{MEDIA_ROOT}}{{ i.npict.url }}"  height="232"></a>  </td>
              <td><a href="{% url 'crm:FlatPhotodel' idd=post.pk sidd=i.pk %}">
                      Удалить</a></td>
              <td><a href="{% url 'crm:FlatPctRotate' idd=post.pk sidd=i.pk %}">
                      Повернуть</a></td>
          </tr>
        </tbody>
        {% endfor %}
    {% endif%}

    <p>
                Выберите не менее 5 картинок<strong> (Нажав кнопку ctr можно выбрать сразу несколько файлов!)</strong>
            </p>
            <input type="file" name="myfiles" multiple>
            {% comment %}<button type="submit" class="btn btn-primary">Сохранить</button>{% endcomment %}


         </div>
         {% for pict in tpict %}<li> {{ pict.npict }}</li> {% endfor %}
      </div><button type="submit" name="_submit" class="btn">Сохранить и продолжить редактирование</button>
   <button type="submit" name="_submit_new" class="btn" >
       Сохранить и создать новый</button>
   <button type="submit" name="_submit_close" class="btn">Сохранить и закрыть</button>
   </div>
</div>
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="/static/material/assets/libs/popper.js/dist/umd/popper.min.js"></script>
<script src="/static/material/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/static/material/materialize.js"></script>
<script>
   document.addEventListener('DOMContentLoaded', function() {
   var elems = document.querySelectorAll('.collapsible');
   var instances = M.Collapsible.init(elems, options);
   });

   // Or with jQuery

   $(document).ready(function(){
   $('.collapsible').collapsible();
   });
</script>
<script>
$('input[type="number"]').on('focus', function(e){
  $(this).on('wheel',function(e){
    e.preventDefault();
  });
});
</script>
{% endblock %}

templates/crm/flat/my_flat_index.html
{% extends 'crm/main.html' %}
{% block content %}
    <div class="row">
      <div class="col-lg-9">
          <div class="card">
                <div class="card-body">

 {% load material_form %}

        <table class="bordered">
        <thead>
          <tr>
              <th>Дата создания</th>
              <th>ID</th>
              <th>Цена</th>
              <th>Район</th>
              <th></th>
          </tr>
        </thead>
{% if tpflatlist %}
{% load el_pagination_tags %}
{% paginate tpflatlist %}
    {% for flatlist in tpflatlist %}
        <tbody>
          <tr>
            <td> {{ flatlist.datep }} </td>
            <td>{{ flatlist.pk }}</td>
            <td> {{ flatlist.cena_agenstv }} </td>
            <td> {{ flatlist.raion }}</td>
            <td><a href="{% url 'crm:flat_detail' idd=flatlist.pk %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Подробнее</button></a></td>
      </tr>

        </tbody>
      </table>

    {% endfor %}

{% show_pages %}

{% else %}
  </tbody></br></br></br>
   <strong>У Вас пока нет обьектов</strong>
{% endif %}
                        </tbody>
      </table>


                </div>
          </div>
      </div>
      <div class="col-lg-3">
          <div class="card">
                <div class="card-body">
                    <form method="post" class="post-form">

                        {% csrf_token %}
                        {% form form=tpflatlist %} {% endform %}
                        <button type="submit" name="_submit" class="btn">Найти</button>
                    </form>
                </div>
          </div>
      </div>

    </div>



<!--
    <ul>
      <li><a href="{% url 'crm:my_flatunpub' %}" class="btn-floating yellow darken-1"title = "Личные"><i class="material-icons">account_box</i></a></li>
      <li><a <a href="{% url 'crm:my_flatpub' %}"  class="btn-floating green" title = "В агенстве"><i class="material-icons">announcement</i></a></li>

    </ul>
-->
  </div>


{% endblock %}