avito/urls.py
from django.conf.urls import url
from . import views


app_name='avito_ap'
urlpatterns = [
    url(r'^avito/index$', views.AvitoIndexView, name='Avito_index'),
    url(r'^avito/detail/(?P<idd>[0-9]+)/$', views.AvitoDetailView, name='Avito_detail'),
    url(r'^avito/new$', views.newAvitoSub, name='Avito_new'),
    url(r'^avito/edit/(?P<idd>[0-9]+)/$', views.AvitoEditSubjView, name='Avito_Edit_Subj'),
    url(r'^avito/edit/obichn/(?P<idd>[0-9]+)/$', views.AvitoBZPubView, name='Avito_Post_Obicn'),
    url(r'^avito/edit/premium/(?P<idd>[0-9]+)/$', views.AvitoPremiumPubView, name='Avito_Post_premium'),
    url(r'^avito/edit/VIP/(?P<idd>[0-9]+)/$', views.AvitoVIPPubView, name='Avito_Post_VIP'),
    url(r'^avito/edit/Podn/(?P<idd>[0-9]+)/$', views.AvitoPodnPubView, name='Avito_Post_Podn'),
    url(r'^avito/edit/Vid/(?P<idd>[0-9]+)/$', views.AvitoVidPubView, name='Avito_Post_Vid'),
    url(r'^avito/edit/Turbo/(?P<idd>[0-9]+)/$', views.AvitoTurboPubView, name='Avito_Post_Turbo'),
    url(r'^avito/edit/Quick/(?P<idd>[0-9]+)/$', views.AvitoQuickPubView, name='Avito_Post_Quick'),
    url(r'^avito/Gal/(?P<idd>[0-9]+)/$', views.AvitoGalView, name='Avito_new_galery'),
    url(r'^avito/del/(?P<idd>[0-9]+)/$', views.AvitoDellView, name='Avito_Del_Subj'),
    url(r'^avito/Gal/del/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$', views.AvitiGalView, name='Avito_del_galery'),
    url(r'^avito/avito.xml$', views.avitoFeedView, name='Avito_feed'),
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.http import request
#from django.views.generic import DetailView,ListView

from . import views


app_name='crm'

urlpatterns = [
    #login
    url(r'^$', views.login_view,  name='login'),
    url(r'^logout/', views.logoutview, name='logout'),



    #news
    url(r'^news/$', views.DashBoardView, name='news_index'),
    #url(r'^news/$', views.zaiyavka_Index_view, name='news_index'),
    url(r'^news/(?P<idd>[0-9]+)/$',views.news_detail_view, name='news_detail'),
    url(r'^news/edit(?P<idd>[0-9]+)/$', views.news_edit_view, name='news_edit'),
    url(r'^news/newnews/$', views.news_postform, name='news_newpost'),

    #flats
    url(r'^flats/newflat/$', views.flat_postForm, name='new_flat'),
    url(r'^flats/newflat_appart/$', views.flat_apparts_postForm, name='flat_apparts_postForm'),#new flat(only for appartaments)
    url(r'^flats/myflats_pub/$', views.my_flatview_pub, name='my_flatpub'), ## All Flats
    url(r'^flats/excl_flats_pub/$', views.excl_flatview_pub, name='excl_flatpub'), ## Exclusive Flats
    url(r'^flats/allflats_pub/$', views.all_flatview_pub, name='all_flatpub'),

    url(r'^flats/vestum/pup/(?P<idd>[0-9]+)/$',views.vestum_pub_view, name='Vs_pub'),
    url(r'^flats/all_vs_pub/$', views.vestum_All_pub_view, name = 'all_vs_pub'),

    url(r'^flats/Seo_flats_pub/$', views.all_flatviewSeo_pub, name='seo_flat_pub'),
    url(r'^flats/Seo_flats_Unpub/$', views.all_flatviewSeo_unpub, name='seo_flat_unpub'),
    url(r'^flats/allflats_pub_form/(?P<idd>[0-9]+)/$', views.seo_flat_pub, name='form_flatpub'),

    url(r'^flats/myflats_unpub/$', views.my_flatview_unpub, name='my_flatunpub'),
    url(r'^flat/edit(?P<idd>[0-9]+)/$', views.my_flatview_edit, name='flat_edit'),
    url(r'^flat/(?P<idd>[0-9]+)/$', views.myflatDetail, name='flat_detail'),
    url(r'^flat/print/(?P<idd>[0-9]+)/$', views.myflatPrint, name='flat_print'),
    url(r'^newFlatGal/(?P<idd>[0-9]+)/$',views.flat_photo_new_view, name='newFlatgal'),
    url(r'^flatdel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.flat_del_view, name='FlatPhotodel'),
    url(r'^flat_rotate/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.FlatPctRotateView, name='FlatPctRotate'),
    ##feeds
    url(r'^domclick.xml$', views.YandexFeedview, name='Yandex'),#for yandex feed
    url(r'^mail.xml$', views.MailRuFeedview, name='Mail'),  # for mail.ru feed
    url(r'^grFeed.xml$', views.GRFeedview, name='Yandex'),  # for yandex feed
    url(r'^domclick1.xml$', views.domclickfeedview, name='domclick'), #for domclick
    url(r'^vestum.xml$', views.vestumfeedview, name='vestumFeed'), #for Vestum 700
    url(r'^vestum300.xml$', views.vestumfeedview300, name='vestumFeed300'),  # for Vestum 300
    url(r'^vestumHouses.xml$', views.vestumFeedViewHouses, name='vestumHouses'),  # for Vestum Houses
    url(r'^sait.xml$', views.sait_vigr_view, name='domclick'), #for sait_feed
    url(r'^newyandex.xml$', views.NewYandexFeedview, name='NewYandex'),  # for New yandex feed(no Fakes)
    url(r'^newsait21.xml$', views.NewSaitFeedview, name='NewSait'),  # for New Sait(21 centry) feed(no Fakes)
    url(r'^afy.xml$', views.AfyFeedview, name='Afy'),  # for New yandex feed(no Fakes)
    ##any
    url(r'^domclick_index/$', views.domclick_Index_view, name='domclick_index'),
    url(r'^kdastr/(?P<idd>[0-9]+)/$', views.kadastr_edit, name='new_kadastr'),# new_kadastr_numb

    #clients
    url(r'^clients/newclient/$', views.new_client_view, name='new_client'),
    url(r'^clients/editclient/(?P<idd>[0-9]+)/$', views.edit_client_view, name='edit_client'),
    url(r'^clients/own_clients/$', views.own_clients_view, name='own_clienws'),
    url(r'^clients/all_clients/$', views.all_clients_view, name='all_clienws'),
    url(r'^clients/otd_clients/$', views.otd_clients_view, name='otd_clienws'),
    url(r'^client/(?P<idd>[0-9]+)/$', views.cliend_detail_view, name='client_detail'),

    #doma
    url(r'^new_dom/$', views.new_dom_view, name='new_dom_post'),
    url(r'^pub_unp_dom/$', views.mu_unpob_doma_view, name='upb_dom_view'),
    url(r'^pub_pub_dom/$', views.mu_pob_doma_view, name='pub_dom_view'),
    url(r'^doms/(?P<idd>[0-9]+)/$',views.dom_detail_view,name='dom_detail'),
    url(r'^doms/edit(?P<idd>[0-9]+)/$', views.domaeditview, name='dom_edit'),
    url(r'^doms/print/(?P<idd>[0-9]+)/$',views.dom_print_view,name='dom_print'),
    url(r'^doms/pct_del/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.house_del_view,name='dom_pct_del'),

    #uchastki
    url(r'^new_uch/$', views.new_uc_view, name='new_uch_post'),
    url(r'^pub_uch/$',views.pup_uchastki,name='pub_uc_index'),
    url(r'^un_uch/$',views.unpup_uchastki,name='unpub_uc_index'),
    url(r'^uch/(?P<idd>[0-9]+)/$',views.uch_detail_view,name='uc_detail'),
    url(r'^uchprt/(?P<idd>[0-9]+)/$',views.uch_print_view,name='uc_print'),
    url(r'^uch/edit(?P<idd>[0-9]+)/$', views.ucheditview, name='uc_edit'),
    url(r'^uch/delete/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$', views.uchastok_del_view, name='uc_delete'),

    #Commerce
    url(r'^commerce/new$', views.NewCommerceView, name='new_commerce_url'),
    url(r'^commerce/my/index$', views.MyIndexCommerceView, name='my_index_commerce_url'),
    url(r'^commerce/all/index$', views.AllIndexCommerceView, name='all_index_commerce_url'),
    url(r'^commerce/detail/(?P<idd>[0-9]+)$', views.DetailCommerceView, name='detail_commerce_url'),
    url(r'^commerce/edit/(?P<idd>[0-9]+)$', views.EditCommerceView, name='edit_commerce_url'),

    #otchet
    url(r'^newotchet/$',views.new_otchet_view_All, name='otch_new_all'),
    url(r'^editotchet/(?P<idd>[0-9]+)/$', views.otchet_edit_view, name='otch_edit'),
    url(r'^allochet(?P<tpr_tab>[0-9]+)/$',views.reeelt_otchet_all_view, name='otch_all_reelt'),
    url(r'^sdelka/(?P<idd>[0-9]+)/$', views.reelt_sdelka_otchet_detail_view, name='otch_detail'),
    url(r'^sdelka/zakrit/(?P<idd>[0-9]+)/$',views.sdelka_zakritie_view, name='sdelka_zakr'),
    url(r'^sdelka/sriv/(?P<idd>[0-9]+)/$',views.sdelka_sriv_view, name='sdelka_sriv'),
    url(r'^sdelka/rasr/(?P<idd>[0-9]+)/$',views.sdelka_rasroch_view, name='sdelka_rasr'),
    url(r'^sdelka/delete/(?P<idd>[0-9]+)/$',views.sdelka_delete_view, name='sdelka_del'),
    url(r'^totchet/$', views.tempFioView,name='1'),#all fio in sdelka edit
    url(r'^testotch/$',views.kach_otch_view,name='DmCahestvoOtch'), #temp for domck kachestvo
    url(r'^perenos_groups/$',views.temp_otch_view, name='tempGroupOtchet'), #for perenos groups

    # feeds
    url(r'^cian.xml$', views.cianfeedview, name='cian'),
    url(r'^ncian.xml$', views.cianfeedview1, name='cian'),#new cian feed
    url(r'^megareal.xml$', views.MegaRealfeedview, name='mega'),
    url(r'^new/$',views.newvigrView, name='newvigr'),
    url(r'^nnew/$',views.newvigrNovostroikaView , name='newNovvigr'),
    url(r'^newviggal/(?P<idd>[0-9]+)/$',views.newVigGalView, name='newvigrgal'),
    url(r'^cianindex/$', views.cianindexview, name='cianindex'),
    url(r'^cianindexup/$', views.cianindexUPview, name='cianindexupl'),
    url(r'^cianedit/(?P<idd>[0-9]+)/$',views.cianedit, name='cianedit'),
    url(r'^ciandels/(?P<idd>[0-9]+)/$',views.cianDelviewSubjct, name='ciandelsubj'),
    url(r'^ciandel/(?P<idd>[0-9]+)/(?P<sidd>[0-9]+)/$',views.ciandelview, name='ciandel'),

    #Zayavki
    url(r'^zayavka/new/$',views.New_Zayavka_View, name='NewZayav'),
    url(r'^zayavka/new_nov/$', views.New_Nov_Zayavka_View, name='NewZayavNov'),
    url(r'^zayavka/new_nov_lich/$', views.lich_rielt_Zayavka_View, name='NewZayavLich'),
    url(r'^index/$',views.zaiyavka_Index_view, name='indexZayavka'),
    url(r'^zayavka/vzyat/(?P<idd>[0-9]+)/$', views.zayavka_vzyata_view, name='VzyatZayav'),
    url(r'^zayavka/sdelka/(?P<idd>[0-9]+)/$', views.zayavka_sdelka_view, name='SdelkaZayav'),
    url(r'^zayavka/sriv/(?P<idd>[0-9]+)/$', views.zayavka_sriv_view, name='SdelkaSriv'),

    #statistika
    url(r'^stat_obj/$', views.stat_count_crm_obj, name='crm_obj_index'),
    url(r'^stat_obj_past/$', views.stat_count_crm_obj_past, name='crm_obj_past_index'),
    url(r'^stat_obj_adler/$', views.stat_count_crm_obj_adler, name='crm_obj_index_adler'),
    url(r'^stat_obj_past_adler/$', views.stat_count_crm_obj_past_adler, name='crm_obj_past_index_adler'),
    url(r'^sdelkaReiting/(?P<year_pr>[0-9]+)/$', views.new_reyting_po_sdelkam,
        name='New_Sdelka_Reit'),
    url(r'^stat_obj/report_in_otdel/(?P<group_pk>[0-9]+)/$', views.ReportInOtdelView, name='report_in_otdel_html'),#
    url(r'^stat_obj/report_in_otdel/all/$', views.ReportAllRieltsView, name='report_all_html'),
    url(r'^stat_obj/report_in_otdel/otdels/$', views.ReportOtdelsView, name='report_otdels_html'),
    url(r'^stat_obj/report_in_otdel/agent/(?P<agent_id>[0-9]+)/$', views.ReportAgentObjectsView, name='agent_report_in_otdel_html'),

    #for homka admin
    url(r'^myadm/$', views.my_admi_view, name = 'myadm'),
    url(r'^myadm/usrbals/(?P<idd>[0-9]+)/$',views.UserBallsAddView, name='usrbalsadd'),
    url(r'^myadm/agent_id/(?P<agent_id>[\w\-]+)/$', views.AgentObjectsView, name='agent_id_url'),
    url(r'^myadm/admin/agent_id/(?P<agent_id>[\w\-]+)/$', views.AdminAgentObjectsView, name='admin_agent_id_url'),
    url(r'^myadm/user_edit/(?P<agent_id>[\w\-]+)/$', views.UserEditView, name='user_edit_url'),
    url(r'^myadm/user_new/$', views.UserNewView, name='user_new_url'),

    # Phone Calls Views
    url(r'^myadm/admin_phone_calls/$', views.AdminPhoneView, name='adm_phone_call'),
    url(r'^myadm/department_phone_calls/(?P<idd>[\w\-]+)/$', views.DepatmentPhoneView, name='department_phone_call'),
    url(r'^myadm/user_phone_calls/(?P<idd>[\w\-]+)/$', views.UserPhoneView, name='user_phone_call'),

    # for Dashboard
    url(r'^dashboard/$', views.DashBoardView, name='DashBoard'),

    #Domcklic texts
    url(r'^dm/index/$', views.dmIndexView, name='dm_index'),
    url(r'^dm/edit/(?P<idd>[0-9]+)/$', views.EditDMtextView, name='dm_edit'),

avito/models.py
from django.core.validators import MinValueValidator
from django.db import models

class avitoflats(models.Model):
    auth = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True)
    DateBegin = models.DateField(verbose_name='Дата начала размещения объявления:',null=True)
    DateEnd = models.DateField(verbose_name='Дата окончания публикации объявления:',null=True)
    Street = models.CharField(verbose_name='Улица:', help_text='Например Гагарина',max_length=55, blank=False)
    House_Numb = models.CharField(verbose_name='Номер дома:', help_text='например 36', max_length=55, blank=False,
                                  null=False)
    Description = models.TextField(verbose_name='Oписание объявления:', blank=False)
    Price = models.IntegerField(verbose_name='Цена в рублях:', default=800000, validators=[MinValueValidator(300000)])
    #AdStatus_ch = (('Free','Обычное'),('Premium','Премиум-объявление;'),('VIP','VIP-объявление'),
    #               ('PushUp','Поднятие объявления в поиске'),('Highlight','Выделение объявления')
    #               ,('TurboSale','Турбо-продажа'),('QuickSale','Быстрая продажа'))
    AdStatus_ch = (('Неопубликованно','Неопубликованно'),('Обычное','Обычное'),('Премиум-объявление','Премиум-объявление')
                   ,('VIP-объявление','VIP-объявление'),('Поднятие объявления в поиске','Поднятие объявления в поиске')
                   ,('Выделение объявления','Выделение объявления')
                   ,('Турбо-продажа','Турбо-продажа'),('Быстрая продажа','Быстрая продажа'))
    AdStatus = models.CharField(verbose_name='Платная услуга:',max_length=55, choices=AdStatus_ch)
    Rooms = models.IntegerField(verbose_name='Количество комнат в квартире:', validators=[MinValueValidator(1)], null=False)
    Square = models.IntegerField(verbose_name='Общая площадь объекта:', blank=False, validators=[MinValueValidator(10)])
    Floor = models.IntegerField(verbose_name='Этаж:', blank=False, validators=[MinValueValidator(1)])
    Floors = models.IntegerField(verbose_name='Количество этажей в доме:', blank=False, validators=[MinValueValidator(1)])
    HouseType_ch = (('Кирпичный','Кирпичный'),('Панельный','Панельный'),('Блочный','Блочный'),
                    ('Монолитный','Монолитный'),('Деревянный','Деревянный'))
    HouseType = models.CharField(verbose_name='Тип дома:',max_length=35, choices=HouseType_ch, blank=False)
    MarketType_ch = (('Вторичка','Вторичка'),('Новостройка','Новостройка'))
    MarketType = models.CharField(verbose_name='Принадлежность квартиры к рынку:', max_length=35, choices=MarketType_ch)
    def __str__(self):
        return self.Street
    class Meta:
        verbose_name = 'Выгрузка на Авито'
        verbose_name_plural = 'Выгрузка на Авито'

class avito_gallery(models.Model):
    id_gal = models.ForeignKey(avitoflats, related_name='idd_gal', verbose_name='Название', on_delete=models.CASCADE)
    date = models.DateField(auto_now=True, verbose_name='Дата создания')
    npict = models.ImageField(verbose_name='Фото объекта', upload_to='image/%Y/%m/%d/avito')
    class Meta:
        verbose_name = 'Выгрузки галерея (Avito)'
        verbose_name_plural = 'Выгрузки галерея (Avito)'

avito/forms.py
from django import forms
from django.core.exceptions import ValidationError

from avito.models import avitoflats, avito_gallery


class AvitoEditForm(forms.ModelForm):
    class Meta:
        model = avitoflats
        fields = ('Street','House_Numb','MarketType','HouseType','Floors','Floor','Rooms','Square',
                  'Price','Description')
    def clean(self):
        cleaned_data = super(AvitoEditForm, self).clean()
        if int(cleaned_data['Floors'])<int(cleaned_data['Floor']):
                raise ValidationError('Этаж больше этажности' , code='invalid')
        return cleaned_data

class AvitoGaleryForm(forms.ModelForm):
    class Meta:
        fields = ('npict',)
        model = avito_gallery

templates/avito/detail.html
{% extends 'crm/main.html' %}

{% block content %}
<div class="row">
<div class="col-lg-12">
    <blockquote> <p class="flow-text">
    <a href="{% url 'avito_ap:Avito_Edit_Subj' idd=tpost.id %} " class="btn" title = "Редактировать">Редактировать</a>
    Статус: {{ tpost.AdStatus }}
        {% if tpost.DateBegin %} ({{ tpost.DateBegin }}- {{ tpost.DateEnd }}){% endif %}
    </p>
    </blockquote>
<div class="card">
<div class="card-body">
	<ul class="nav nav-pills m-t-30 m-b-30">
    <li class=" nav-item"> <a href="#test1" class="nav-link active" data-toggle="tab" aria-expanded="false">Главное</a> </li>
	<li class="nav-item"> <a href="#test5" class="nav-link" data-toggle="tab" aria-expanded="true">Фото</a> </li>
    </ul>
<div class="tab-content br-n pn">
    <div id="test1" class="tab-pane active">
	<div class="p-20" ><p> </p></div>
    <div class="row">
	<table class="bordered">
        <tbody>

          <tr>
            <td>Адрес: </td>
            <td><strong>ул.{{ tpost.Street }} дом №{{ tpost.House_Numb }}</strong> </td>
          </tr>
          <tr>
            <td>Принадлежность квартиры к рынку:</td>
            <td><strong>{{ tpost.MarketType  }}</strong></td>
          </tr>
                    <tr>
            <td>Тип дома:</td>
            <td><strong> {{ tpost.HouseType }}</strong></td>
          </tr>
          <tr>
            <td>Количество этажей в доме:</td>
            <td><strong>{{ tpost.Floors }} </strong></td>
          </tr>
          <tr>
            <td>Этаж:</td>
            <td><strong>{{ tpost.Floor }} </strong></td>
          </tr>
          <tr>
            <td>Общая площадь объекта:</td>
            <td><strong>{{ tpost.Square }} метр</strong></td>
          </tr>
          <tr>
            <td>Цена в рублях:</td>
            <td><strong>{{ tpost.Price }} руб.</strong></td>
          </tr>
          <tr>
            <td>Oписание объявления:</td>
            <td><strong>{{ tpost.Description }} </strong></td>
          </tr>
        </tbody>
      </table>
</div>
</div>


<div id="test5" class="tab-pane">
	<div class="p-20" ><p> </p></div>
    <div class="row">
        {% for i in tpost.idd_gal.all %}
            <div style="float:left; margin-right:10px; margin-top:10px;"> <img class="materialboxed" rel="gallery" height="250" src="http://77.222.63.160{{ i.npict.url }}"></div>
        {% endfor %}
</div>
</div>



</div>
</div>
</div>
</div>

<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-body">
<blockquote>Применить услуги:</br>

{% if request.user.userprofile1.vestum_count_ads != 0 and tpost.AdStatus == 'Неопубликованно' %}
    <a href="{% url 'avito_ap:Avito_Post_Obicn' idd=tpost.id %} " class="btn" title = "Обычное об.">Обычное об.</a>
{% endif %}

{% if request.user.userprofile1.avitoPR_count_ads != 0 and tpost.AdStatus != 'Премиум-объявление' and tpost.AdStatus != 'Неопубликованно'%}
    <a href="{% url 'avito_ap:Avito_Post_premium' idd=tpost.id %} " class="btn" title = "Премиум">Премиум</a>
{% endif %}

{% if request.user.userprofile1.avitoVIP_count_ads != 0 and tpost.AdStatus != 'VIP-объявление'  and tpost.AdStatus != 'Неопубликованно'%}
    <a href="{% url 'avito_ap:Avito_Post_VIP' idd=tpost.id %} " class="btn" title = "VIP">VIP</a>
{% endif %}

{% if request.user.userprofile1.avitoPODN_count_ads != 0 and tpost.AdStatus != 'Поднятие объявления в поиске' and tpost.AdStatus != 'Неопубликованно' %}
    <a href="{% url 'avito_ap:Avito_Post_Podn' idd=tpost.id %} " class="btn" title = "Поднятие в поиске">Поднятие в поиске</a>
{% endif %}

{% if request.user.userprofile1.avitoVID_count_ads != 0 and tpost.AdStatus != 'Выделение объявления' and tpost.AdStatus != 'Неопубликованно' %}
    <a href="{% url 'avito_ap:Avito_Post_Vid' idd=tpost.id %} " class="btn" title = "Выделение">Выделение</a>
{% endif %}

{% if request.user.userprofile1.avitoTURBO_count_ads != 0 and tpost.AdStatus != 'Турбо-продажа' and tpost.AdStatus != 'Неопубликованно' %}
    <a href="{% url 'avito_ap:Avito_Post_Turbo' idd=tpost.id %} " class="btn" title = "Турбо-продажа">Турбо-продажа</a>
{% endif %}

{% if request.user.userprofile1.avitoQUICK_count_ads != 0 and tpost.AdStatus != 'Быстрая продажа' and tpost.AdStatus != 'Неопубликованно' %}
    <a href="{% url 'avito_ap:Avito_Post_Quick' idd=tpost.id %} " class="btn" title = "Быстрая продажа">Быстрая продажа</a>
{% endif %}

</blockquote>
</div>
</div>
</div>
</div>
		<script src="/static/material/js/jquery.js"></script>
		<script src="/static/material/js/materialize.admin.min.js"></script>

{% load el_pagination_tags %}





  </div>

{% endblock %}

templates/avito/edit.html
{% extends 'crm/main.html' %}
{% block content %}
{% load material_form %}
    <div class="row">
         <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form method="post" class="post-form">
                    {% csrf_token %}
                        {% form form=tform layout=form.layout%}{% endform %}
                        <button type="submit" name="_submit" class="btn">Сохранить и добавить фото</button>
                </div>
            </div>
         </div>
     </div>

</form>

{% endblock %}

templates/avito/index.html
{% extends 'crm/main.html' %}
{% block content %}
    <div class="row">
      <div class="col-lg-12">
          <div class="card">
               <div class="card-content">

        <table class="bordered">
        <thead>
          <tr>
              <th>Дата начала публикации</th>
              <th>Дата окончания публикации</th>
              <th>Статус</th>
              <th>Адрес</th>
              <th>Цена</th>
			  <th></th>
			  <th></th>
              <th></th>
          </tr>
        </thead>


   {% if tpost %}

    {% for post in tpost %}
        <tbody>
          <tr>
            <td>{% if post.DateBegin %} {{ post.DateBegin }}
                {% else %}{% endif %} </td>
            <td>{% if post.DateEnd %} {{ post.DateEnd }}
                {% else %}{% endif %}</td>
            <td> {% if post.AdStatus == 'Неопубликованно' or post.DateEnd > tdate %}<span class="new badge red" data-badge-caption="">Неопубликованно</span>
                {% else %}{{ post.AdStatus }}{% endif %} </td>
            <td> {{ post.Street }} д.{{ post.House_Numb }}</td>
            <td>{{ post.Price }}</td>
            <td><a href="{% url 'avito_ap:Avito_detail' idd=post.pk %}"><button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-edit"></span>Просмотр</button></a></td>

            <td><a href="{% url 'avito_ap:Avito_Edit_Subj' idd=post.pk %}"><button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-edit"></span>Редактировать</button></a></td>
            <td><a href="{% url 'avito_ap:Avito_Del_Subj' idd=post.pk %}"><button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-edit"></span>Удалить</button></a></td>
              {% comment %}
            <td><a href="{% url 'crm:newvigrgal' idd=sp.pk %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>фото</button></a></td>
            <td><a href="{% url 'crm:ciandelsubj' idd=sp.pk %}"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>Удалить</button></a></td>
            {% endcomment %}
          </tr>

        </tbody>


    {% endfor %}
 </table>
  {% endif %}
               </div>
          </div>
    </div>
{% endblock %}